# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BillingProjectResponse")

model.instance <- BillingProjectResponse$new()

test_that("projectName", {
  # tests for the property `projectName` (character)
  # the name of the project

  # uncomment below to test the property 
  #expect_equal(model.instance$`projectName`, "EXPECTED_RESULT")
})

test_that("billingAccount", {
  # tests for the property `billingAccount` (character)
  # the billing account to use in google projects

  # uncomment below to test the property 
  #expect_equal(model.instance$`billingAccount`, "EXPECTED_RESULT")
})

test_that("servicePerimeter", {
  # tests for the property `servicePerimeter` (character)
  # the name of the service permeters for google project

  # uncomment below to test the property 
  #expect_equal(model.instance$`servicePerimeter`, "EXPECTED_RESULT")
})

test_that("invalidBillingAccount", {
  # tests for the property `invalidBillingAccount` (character)
  # whether or not the billing account is usable by Terra

  # uncomment below to test the property 
  #expect_equal(model.instance$`invalidBillingAccount`, "EXPECTED_RESULT")
})

test_that("roles", {
  # tests for the property `roles` (array[character])
  # the roles the caller has on the project

  # uncomment below to test the property 
  #expect_equal(model.instance$`roles`, "EXPECTED_RESULT")
})

