# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FailureMessage")

model.instance <- FailureMessage$new()

test_that("failure", {
  # tests for the property `failure` (character)
  # The failure message

  # uncomment below to test the property 
  #expect_equal(model.instance$`failure`, "EXPECTED_RESULT")
})

test_that("timestamp", {
  # tests for the property `timestamp` (character)
  # The time at which this failure occurred

  # uncomment below to test the property 
  #expect_equal(model.instance$`timestamp`, "EXPECTED_RESULT")
})

