# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateAttributeEntityReferenceList")

model.instance <- CreateAttributeEntityReferenceList$new()

test_that("op", {
  # tests for the property `op` (character)
  # The operation to perform on the attribute

  # uncomment below to test the property 
  #expect_equal(model.instance$`op`, "EXPECTED_RESULT")
})

test_that("attributeListName", {
  # tests for the property `attributeListName` (character)
  # The name of the empty attribute entity-reference list to create. This is a non-destructive operation.

  # uncomment below to test the property 
  #expect_equal(model.instance$`attributeListName`, "EXPECTED_RESULT")
})

