# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateAttributeValueList")

model.instance <- CreateAttributeValueList$new()

test_that("op", {
  # tests for the property `op` (character)
  # The operation to perform on the attribute

  # uncomment below to test the property 
  #expect_equal(model.instance$`op`, "EXPECTED_RESULT")
})

test_that("attributeName", {
  # tests for the property `attributeName` (character)
  # The name of the empty attribute value-list to create. This is a non-destructive operation.

  # uncomment below to test the property 
  #expect_equal(model.instance$`attributeName`, "EXPECTED_RESULT")
})

