# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test WorkspaceCatalogUpdateResponseList")

model.instance <- WorkspaceCatalogUpdateResponseList$new()

test_that("usersUpdated", {
  # tests for the property `usersUpdated` (array[WorkspaceCatalogResponse])
  # the users or groups who were updated

  # uncomment below to test the property 
  #expect_equal(model.instance$`usersUpdated`, "EXPECTED_RESULT")
})

test_that("emailsNotFound", {
  # tests for the property `emailsNotFound` (array[character])
  # the emails of users or groups who were not found

  # uncomment below to test the property 
  #expect_equal(model.instance$`emailsNotFound`, "EXPECTED_RESULT")
})

