# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AddListMember")

model.instance <- AddListMember$new()

test_that("op", {
  # tests for the property `op` (character)
  # The operation to perform on the attribute

  # uncomment below to test the property 
  #expect_equal(model.instance$`op`, "EXPECTED_RESULT")
})

test_that("attributeListName", {
  # tests for the property `attributeListName` (character)
  # The name of the attribute list

  # uncomment below to test the property 
  #expect_equal(model.instance$`attributeListName`, "EXPECTED_RESULT")
})

test_that("newMember", {
  # tests for the property `newMember` (character)
  # The attribute to add to the list

  # uncomment below to test the property 
  #expect_equal(model.instance$`newMember`, "EXPECTED_RESULT")
})

