# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ConfigurationPayloadMethodRepoMethod")

model.instance <- ConfigurationPayloadMethodRepoMethod$new()

test_that("methodName", {
  # tests for the property `methodName` (character)
  # Name of referenced method

  # uncomment below to test the property 
  #expect_equal(model.instance$`methodName`, "EXPECTED_RESULT")
})

test_that("methodNamespace", {
  # tests for the property `methodNamespace` (character)
  # Namespace of referenced method

  # uncomment below to test the property 
  #expect_equal(model.instance$`methodNamespace`, "EXPECTED_RESULT")
})

test_that("methodVersion", {
  # tests for the property `methodVersion` (integer)
  # Snapshot ID of referenced method

  # uncomment below to test the property 
  #expect_equal(model.instance$`methodVersion`, "EXPECTED_RESULT")
})

