# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MethodAclPair")

model.instance <- MethodAclPair$new()

test_that("method", {
  # tests for the property `method` (MethodRepoMethod)

  # uncomment below to test the property 
  #expect_equal(model.instance$`method`, "EXPECTED_RESULT")
})

test_that("acls", {
  # tests for the property `acls` (array[FireCloudPermission])

  # uncomment below to test the property 
  #expect_equal(model.instance$`acls`, "EXPECTED_RESULT")
})

test_that("message", {
  # tests for the property `message` (character)
  # ignored during input; if present during output, contains error messages

  # uncomment below to test the property 
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

