# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Tool")

model.instance <- Tool$new()

test_that("url", {
  # tests for the property `url` (character)
  # The URL for this tool in this registry, for example &#x60;http://agora.broadinstitute.org/tools/123456&#x60;

  # uncomment below to test the property 
  #expect_equal(model.instance$`url`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (character)
  # A unique identifier of the tool, scoped to this registry, for example &#x60;123456&#x60; or &#x60;123456_v1&#x60;

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("organization", {
  # tests for the property `organization` (character)
  # The organization that published the image.

  # uncomment below to test the property 
  #expect_equal(model.instance$`organization`, "EXPECTED_RESULT")
})

test_that("toolname", {
  # tests for the property `toolname` (character)
  # The name of the tool.

  # uncomment below to test the property 
  #expect_equal(model.instance$`toolname`, "EXPECTED_RESULT")
})

test_that("toolclass", {
  # tests for the property `toolclass` (ToolClass)

  # uncomment below to test the property 
  #expect_equal(model.instance$`toolclass`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # The description of the tool.

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("author", {
  # tests for the property `author` (character)
  # Contact information for the author of this tool entry in the registry. (More complex authorship information is handled by the descriptor)

  # uncomment below to test the property 
  #expect_equal(model.instance$`author`, "EXPECTED_RESULT")
})

test_that("meta-version", {
  # tests for the property `meta-version` (character)
  # The version of this tool in the registry. Iterates when fields like the description, author, etc. are updated.

  # uncomment below to test the property 
  #expect_equal(model.instance$`meta-version`, "EXPECTED_RESULT")
})

test_that("contains", {
  # tests for the property `contains` (array[character])
  # An array of IDs for the applications that are stored inside this tool (for example &#x60;https://bio.tools/tool/mytum.de/SNAP2/1&#x60;). This always returns an empty array.

  # uncomment below to test the property 
  #expect_equal(model.instance$`contains`, "EXPECTED_RESULT")
})

test_that("verified", {
  # tests for the property `verified` (character)
  # Reports whether this tool has been verified by a specific organization or individual.  This always returns false.

  # uncomment below to test the property 
  #expect_equal(model.instance$`verified`, "EXPECTED_RESULT")
})

test_that("verified-source", {
  # tests for the property `verified-source` (character)
  # Source of metadata that can support a verified tool, such as an email or URL

  # uncomment below to test the property 
  #expect_equal(model.instance$`verified-source`, "EXPECTED_RESULT")
})

test_that("signed", {
  # tests for the property `signed` (character)
  # Reports whether this tool has been signed.  This always returns false.

  # uncomment below to test the property 
  #expect_equal(model.instance$`signed`, "EXPECTED_RESULT")
})

test_that("versions", {
  # tests for the property `versions` (array[ToolVersion])
  # A list of versions for this tool

  # uncomment below to test the property 
  #expect_equal(model.instance$`versions`, "EXPECTED_RESULT")
})

