# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SubmissionValidationValue")

model.instance <- SubmissionValidationValue$new()

test_that("value", {
  # tests for the property `value` (character)
  # the value of the input expression for the specified entity

  # uncomment below to test the property 
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

test_that("error", {
  # tests for the property `error` (character)
  # parsing error(s)

  # uncomment below to test the property 
  #expect_equal(model.instance$`error`, "EXPECTED_RESULT")
})

test_that("inputName", {
  # tests for the property `inputName` (character)
  # name of input

  # uncomment below to test the property 
  #expect_equal(model.instance$`inputName`, "EXPECTED_RESULT")
})

