# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ConfigurationResponseWithPayloadObject")

model.instance <- ConfigurationResponseWithPayloadObject$new()

test_that("namespace", {
  # tests for the property `namespace` (character)
  # Namespace which contains AgoraEntity.

  # uncomment below to test the property 
  #expect_equal(model.instance$`namespace`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # Name of the AgoraEntity.

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("snapshotId", {
  # tests for the property `snapshotId` (integer)
  # SnapshotId of AgoraEntity

  # uncomment below to test the property 
  #expect_equal(model.instance$`snapshotId`, "EXPECTED_RESULT")
})

test_that("snapshotComment", {
  # tests for the property `snapshotComment` (character)
  # Snapshot comment of AgoraEntity

  # uncomment below to test the property 
  #expect_equal(model.instance$`snapshotComment`, "EXPECTED_RESULT")
})

test_that("synopsis", {
  # tests for the property `synopsis` (character)
  # Synopsis which contains AgoraEntity.

  # uncomment below to test the property 
  #expect_equal(model.instance$`synopsis`, "EXPECTED_RESULT")
})

test_that("documentation", {
  # tests for the property `documentation` (character)
  # Documentation of the AgoraEntity. MUST BE REQUESTED EXPLICITLY.

  # uncomment below to test the property 
  #expect_equal(model.instance$`documentation`, "EXPECTED_RESULT")
})

test_that("createDate", {
  # tests for the property `createDate` (character)
  # Timestamp of creation

  # uncomment below to test the property 
  #expect_equal(model.instance$`createDate`, "EXPECTED_RESULT")
})

test_that("url", {
  # tests for the property `url` (character)
  # URL where resource can be accessed.

  # uncomment below to test the property 
  #expect_equal(model.instance$`url`, "EXPECTED_RESULT")
})

test_that("payloadObject", {
  # tests for the property `payloadObject` (ConfigurationPayload)

  # uncomment below to test the property 
  #expect_equal(model.instance$`payloadObject`, "EXPECTED_RESULT")
})

test_that("entityType", {
  # tests for the property `entityType` (character)
  # Type of the AgoraEntity -- Task or Workflow.

  # uncomment below to test the property 
  #expect_equal(model.instance$`entityType`, "EXPECTED_RESULT")
})

