# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Consent")

model.instance <- Consent$new()

test_that("consentId", {
  # tests for the property `consentId` (character)
  # The ID of the entity.

  # uncomment below to test the property 
  #expect_equal(model.instance$`consentId`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # Name used to identify the consent.

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("createDate", {
  # tests for the property `createDate` (integer)
  # Creation Date in date-time milliseconds

  # uncomment below to test the property 
  #expect_equal(model.instance$`createDate`, "EXPECTED_RESULT")
})

test_that("lastUpdate", {
  # tests for the property `lastUpdate` (integer)
  # Date of the last update in date-time milliseconds

  # uncomment below to test the property 
  #expect_equal(model.instance$`lastUpdate`, "EXPECTED_RESULT")
})

test_that("sortDate", {
  # tests for the property `sortDate` (integer)
  # The lastest modification date in date-time milliseconds

  # uncomment below to test the property 
  #expect_equal(model.instance$`sortDate`, "EXPECTED_RESULT")
})

test_that("requiresManualReview", {
  # tests for the property `requiresManualReview` (character)
  # Describes if this consent has to be reviewed manually.

  # uncomment below to test the property 
  #expect_equal(model.instance$`requiresManualReview`, "EXPECTED_RESULT")
})

test_that("dataUseLetter", {
  # tests for the property `dataUseLetter` (character)
  # The URL of the saved file.

  # uncomment below to test the property 
  #expect_equal(model.instance$`dataUseLetter`, "EXPECTED_RESULT")
})

test_that("useRestriction", {
  # tests for the property `useRestriction` (map(object))
  # The UseRestriction of this consent. Used to match against another entities.

  # uncomment below to test the property 
  #expect_equal(model.instance$`useRestriction`, "EXPECTED_RESULT")
})

test_that("dulName", {
  # tests for the property `dulName` (character)
  # Name that identifies the Data Use Letter file.

  # uncomment below to test the property 
  #expect_equal(model.instance$`dulName`, "EXPECTED_RESULT")
})

test_that("translatedUseRestriction", {
  # tests for the property `translatedUseRestriction` (character)
  # The translated use restriction of the consent.

  # uncomment below to test the property 
  #expect_equal(model.instance$`translatedUseRestriction`, "EXPECTED_RESULT")
})

