# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OAuthApi")

api.instance <- OAuthApi$new()

test_that("GetRefreshTokenStatus", {
  # tests for GetRefreshTokenStatus
  # base path: http://localhost
  # deprecated
  # This API is a deprecated noop. Previously, it returned the status of the current user&#39;s refresh token. Since refresh tokens are no longer used in the back end, this API is now hardcoded to respond as if the user&#39;s refresh token is valid. This API may be removed in a future release. 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("HandleOauthCode", {
  # tests for HandleOauthCode
  # base path: http://localhost
  # deprecated
  # This API is a deprecated noop. Previously, it allowed the server to acquire a refresh token. Since refresh tokens are no longer used in the back end, this API is now hardcoded to respond as if it successfully acquired a refresh token, without doing any actual work. This API may be removed in a future release. 
  # @param body InlineObject5  (optional)
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

