# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GA4GHToolRegistryApi")

api.instance <- GA4GHToolRegistryApi$new()

test_that("Ga4ghV1MetadataGet", {
  # tests for Ga4ghV1MetadataGet
  # base path: http://localhost
  # Return some metadata that is useful for describing this registry
  # Return some metadata that is useful for describing this registry
  # @return [Metadata]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Ga4ghV1ToolClassesGet", {
  # tests for Ga4ghV1ToolClassesGet
  # base path: http://localhost
  # List all tool types
  # This endpoint returns all tool-classes available 
  # @return [array[ToolClass]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Ga4ghV1ToolsGet", {
  # tests for Ga4ghV1ToolsGet
  # base path: http://localhost
  # List all tools
  # This endpoint returns all tools available. 
  # @return [array[Tool]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Ga4ghV1ToolsIdGet", {
  # tests for Ga4ghV1ToolsIdGet
  # base path: http://localhost
  # List one specific tool, acts as an anchor for self references
  # This endpoint returns one specific tool (which has ToolVersions nested inside it)
  # @param id character A unique identifier of the tool, scoped to this registry, for example `123456`
  # @return [Tool]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Ga4ghV1ToolsIdVersionsGet", {
  # tests for Ga4ghV1ToolsIdVersionsGet
  # base path: http://localhost
  # List versions of a tool
  # Returns all versions of the specified tool
  # @param id character A unique identifier of the tool, scoped to this registry, for example `123456`
  # @return [array[ToolVersion]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Ga4ghV1ToolsIdVersionsVersionIdGet", {
  # tests for Ga4ghV1ToolsIdVersionsVersionIdGet
  # base path: http://localhost
  # List one specific tool version, acts as an anchor for self references
  # This endpoint returns one specific tool version
  # @param id character A unique identifier of the tool, scoped to this registry, for example `123456`
  # @param version.id character An identifier of the tool version, scoped to this registry, for example `v1`
  # @return [ToolVersion]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Ga4ghV1ToolsIdVersionsVersionIdTypeDescriptorGet", {
  # tests for Ga4ghV1ToolsIdVersionsVersionIdTypeDescriptorGet
  # base path: http://localhost
  # Get the tool descriptor (WDL) for the specified tool.
  # Returns the WDL descriptor for the specified tool.
  # @param type character The output type of the descriptor. If not specified it is up to the underlying implementation to determine which output type to return. Plain types return the bare descriptor while the \"non-plain\" types return a descriptor wrapped with metadata. 
  # @param id character A unique identifier of the tool, scoped to this registry, for example `123456`.    *In FireCloud, this must be a namespace + \":\" + name. For instance, if your namespace   is 'foo' and name is 'bar', this must be 'foo:bar'.* 
  # @param version.id character An identifier of the tool version for this particular tool registry, for example `v1`.    *In FireCloud, this must be an integer representing the FireCloud snapshot id.* 
  # @return [ToolDescriptor]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

