# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ManagedGroupWithMembers")

model.instance <- ManagedGroupWithMembers$new()

test_that("membersGroup", {
  # tests for the property `membersGroup` (RawlsGroupShort)

  # uncomment below to test the property 
  #expect_equal(model.instance$`membersGroup`, "EXPECTED_RESULT")
})

test_that("adminsGroup", {
  # tests for the property `adminsGroup` (RawlsGroupShort)

  # uncomment below to test the property 
  #expect_equal(model.instance$`adminsGroup`, "EXPECTED_RESULT")
})

test_that("membersEmails", {
  # tests for the property `membersEmails` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`membersEmails`, "EXPECTED_RESULT")
})

test_that("adminsEmails", {
  # tests for the property `adminsEmails` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`adminsEmails`, "EXPECTED_RESULT")
})

