# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ValidatedMethodConfiguration")

model.instance <- ValidatedMethodConfiguration$new()

test_that("validInputs", {
  # tests for the property `validInputs` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`validInputs`, "EXPECTED_RESULT")
})

test_that("invalidInputs", {
  # tests for the property `invalidInputs` (map(object))

  # uncomment below to test the property 
  #expect_equal(model.instance$`invalidInputs`, "EXPECTED_RESULT")
})

test_that("missingInputs", {
  # tests for the property `missingInputs` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`missingInputs`, "EXPECTED_RESULT")
})

test_that("extraInputs", {
  # tests for the property `extraInputs` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`extraInputs`, "EXPECTED_RESULT")
})

test_that("validOutputs", {
  # tests for the property `validOutputs` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`validOutputs`, "EXPECTED_RESULT")
})

test_that("invalidOutputs", {
  # tests for the property `invalidOutputs` (map(object))

  # uncomment below to test the property 
  #expect_equal(model.instance$`invalidOutputs`, "EXPECTED_RESULT")
})

test_that("methodConfiguration", {
  # tests for the property `methodConfiguration` (MethodConfiguration)

  # uncomment below to test the property 
  #expect_equal(model.instance$`methodConfiguration`, "EXPECTED_RESULT")
})

