# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AttributeEntityReference")

model.instance <- AttributeEntityReference$new()

test_that("entityType", {
  # tests for the property `entityType` (character)
  # The type of the entity

  # uncomment below to test the property 
  #expect_equal(model.instance$`entityType`, "EXPECTED_RESULT")
})

test_that("entityName", {
  # tests for the property `entityName` (character)
  # The name of the entity

  # uncomment below to test the property 
  #expect_equal(model.instance$`entityName`, "EXPECTED_RESULT")
})

