# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NotificationType")

model.instance <- NotificationType$new()

test_that("notificationKey", {
  # tests for the property `notificationKey` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`notificationKey`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

