# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test WorkflowQueryParameter")

model.instance <- WorkflowQueryParameter$new()

test_that("start", {
  # tests for the property `start` (character)
  # Returns only workflows with an equal or later start datetime.  Can be specified at most once. If both start and end date are specified, start date must be before or equal to end date. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`start`, "EXPECTED_RESULT")
})

test_that("end", {
  # tests for the property `end` (character)
  # Returns only workflows with an equal or earlier end datetime.  Can be specified at most once. If both start and end date are specified, start date must be before or equal to end date. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`end`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (character)
  # Returns only workflows with the specified status.  If specified multiple times, returns workflows in any of the specified statuses. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # Returns only workflows with the specified name.  If specified multiple times, returns workflows with any of the specified names. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (character)
  # Returns only workflows with the specified workflow id.  If specified multiple times, returns workflows with any of the specified workflow ids. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

