# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RemoveAttributeAllOf")

model.instance <- RemoveAttributeAllOf$new()

test_that("attributeName", {
  # tests for the property `attributeName` (character)
  # The name of attribute to remove

  # uncomment below to test the property 
  #expect_equal(model.instance$`attributeName`, "EXPECTED_RESULT")
})

