# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EntityQueryParameters")

model.instance <- EntityQueryParameters$new()

test_that("page", {
  # tests for the property `page` (integer)
  # page number, 1-indexed positive integer

  # uncomment below to test the property 
  #expect_equal(model.instance$`page`, "EXPECTED_RESULT")
})

test_that("pageSize", {
  # tests for the property `pageSize` (integer)
  # count of items per page, positive integer

  # uncomment below to test the property 
  #expect_equal(model.instance$`pageSize`, "EXPECTED_RESULT")
})

test_that("sortField", {
  # tests for the property `sortField` (character)
  # field to sort by

  # uncomment below to test the property 
  #expect_equal(model.instance$`sortField`, "EXPECTED_RESULT")
})

test_that("sortDirection", {
  # tests for the property `sortDirection` (character)
  # asc or desc

  # uncomment below to test the property 
  #expect_equal(model.instance$`sortDirection`, "EXPECTED_RESULT")
})

test_that("filterTerms", {
  # tests for the property `filterTerms` (character)
  # terms to filter results by

  # uncomment below to test the property 
  #expect_equal(model.instance$`filterTerms`, "EXPECTED_RESULT")
})

