# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AddUpdateAttributeAllOf")

model.instance <- AddUpdateAttributeAllOf$new()

test_that("attributeName", {
  # tests for the property `attributeName` (character)
  # Name of attribute to add/update

  # uncomment below to test the property 
  #expect_equal(model.instance$`attributeName`, "EXPECTED_RESULT")
})

test_that("addUpdateAttribute", {
  # tests for the property `addUpdateAttribute` (character)
  # Value to add/update. Accepts strings, numbers, booleans.

  # uncomment below to test the property 
  #expect_equal(model.instance$`addUpdateAttribute`, "EXPECTED_RESULT")
})

