# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LabelsResponse")

model.instance <- LabelsResponse$new()

test_that("id", {
  # tests for the property `id` (character)
  # The identifier of the workflow

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("labels", {
  # tests for the property `labels` (character)
  # The custom labels as json

  # uncomment below to test the property 
  #expect_equal(model.instance$`labels`, "EXPECTED_RESULT")
})

