# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test WorkflowQueryResponse")

model.instance <- WorkflowQueryResponse$new()

test_that("results", {
  # tests for the property `results` (array[WorkflowQueryResult])

  # uncomment below to test the property 
  #expect_equal(model.instance$`results`, "EXPECTED_RESULT")
})

