# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ToolOutputParameter")

model.instance <- ToolOutputParameter$new()

test_that("name", {
  # tests for the property `name` (character)
  # The name of this input value (formatted as expected by the tool)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("valueType", {
  # tests for the property `valueType` (ValueType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`valueType`, "EXPECTED_RESULT")
})

