# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BagitRequest")

model.instance <- BagitRequest$new()

test_that("bagitURL", {
  # tests for the property `bagitURL` (character)
  # link to publically accessible zipped BagIt directory

  # uncomment below to test the property 
  #expect_equal(model.instance$`bagitURL`, "EXPECTED_RESULT")
})

test_that("format", {
  # tests for the property `format` (character)
  # the type of the files inside the bagit. Currently this must be the string \&quot;TSV\&quot;.

  # uncomment below to test the property 
  #expect_equal(model.instance$`format`, "EXPECTED_RESULT")
})

