# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BillingProjectStatus")

model.instance <- BillingProjectStatus$new()

test_that("projectName", {
  # tests for the property `projectName` (character)
  # the name of the billing project

  # uncomment below to test the property 
  #expect_equal(model.instance$`projectName`, "EXPECTED_RESULT")
})

test_that("creationStatus", {
  # tests for the property `creationStatus` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`creationStatus`, "EXPECTED_RESULT")
})

