# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UserImportPermission")

model.instance <- UserImportPermission$new()

test_that("billingProject", {
  # tests for the property `billingProject` (character)
  # does the user have at least one ready billing project?

  # uncomment below to test the property 
  #expect_equal(model.instance$`billingProject`, "EXPECTED_RESULT")
})

test_that("writableWorkspace", {
  # tests for the property `writableWorkspace` (character)
  # does the user have at least one writable workspace?

  # uncomment below to test the property 
  #expect_equal(model.instance$`writableWorkspace`, "EXPECTED_RESULT")
})

