# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SubmissionValidationInput")

model.instance <- SubmissionValidationInput$new()

test_that("wdlName", {
  # tests for the property `wdlName` (character)
  # name of input

  # uncomment below to test the property 
  #expect_equal(model.instance$`wdlName`, "EXPECTED_RESULT")
})

test_that("expression", {
  # tests for the property `expression` (character)
  # expression for input

  # uncomment below to test the property 
  #expect_equal(model.instance$`expression`, "EXPECTED_RESULT")
})

