# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PFBRequest")

model.instance <- PFBRequest$new()

test_that("url", {
  # tests for the property `url` (character)
  # link to publically accessible PFB/Avro

  # uncomment below to test the property 
  #expect_equal(model.instance$`url`, "EXPECTED_RESULT")
})

