# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Enabled")

model.instance <- Enabled$new()

test_that("google", {
  # tests for the property `google` (character)
  # User enabled via Google?

  # uncomment below to test the property 
  #expect_equal(model.instance$`google`, "EXPECTED_RESULT")
})

test_that("ldap", {
  # tests for the property `ldap` (character)
  # User enabled in LDAP?

  # uncomment below to test the property 
  #expect_equal(model.instance$`ldap`, "EXPECTED_RESULT")
})

test_that("allUsersGroup", {
  # tests for the property `allUsersGroup` (character)
  # User is a member of the \&quot;All Users\&quot; group?

  # uncomment below to test the property 
  #expect_equal(model.instance$`allUsersGroup`, "EXPECTED_RESULT")
})

