# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BillingV2Api")

api.instance <- BillingV2Api$new()

test_that("AddUserToBillingProject", {
  # tests for AddUserToBillingProject
  # base path: http://localhost
  # add user or group to billing project the caller owns
  # add user or group to billing project the caller owns
  # @param project.id character Project ID
  # @param workbench.role character role of user for project
  # @param email character email of user or group to add
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateBillingProjectFullV2", {
  # tests for CreateBillingProjectFullV2
  # base path: http://localhost
  # create billing project in rawls
  # create new billing project in rawls
  # @param create.project.request CreateRawlsBillingProjectFullRequest create project request
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteBillingProject", {
  # tests for DeleteBillingProject
  # base path: http://localhost
  # delete billing project
  # delete billing project
  # @param project.id character Id of the billing project
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetBillingProject", {
  # tests for GetBillingProject
  # base path: http://localhost
  # get billing project
  # get billing project
  # @param project.id character Id of the billing project
  # @return [BillingProjectResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListBillingProjectMembers", {
  # tests for ListBillingProjectMembers
  # base path: http://localhost
  # list members of billing project the caller owns
  # list members of billing project the caller owns
  # @param project.id character Project ID
  # @return [array[BillingProjectMember]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RemoveUserFromBillingProject", {
  # tests for RemoveUserFromBillingProject
  # base path: http://localhost
  # remove user or group from billing project the caller owns
  # remove user or group from billing project the caller owns
  # @param project.id character Project ID
  # @param workbench.role character role of user for project
  # @param email character email of user or group to remove
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

