# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EntitySoftConflict")

model.instance <- EntitySoftConflict$new()

test_that("entityType", {
  # tests for the property `entityType` (character)
  # the type of the entity

  # uncomment below to test the property 
  #expect_equal(model.instance$`entityType`, "EXPECTED_RESULT")
})

test_that("entityName", {
  # tests for the property `entityName` (character)
  # the name of the entity

  # uncomment below to test the property 
  #expect_equal(model.instance$`entityName`, "EXPECTED_RESULT")
})

test_that("conflicts", {
  # tests for the property `conflicts` (array[EntitySoftConflict])
  # the next entity in the path to the conflict

  # uncomment below to test the property 
  #expect_equal(model.instance$`conflicts`, "EXPECTED_RESULT")
})

