# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BillingProjectMembership")

model.instance <- BillingProjectMembership$new()

test_that("projectName", {
  # tests for the property `projectName` (character)
  # the name of the project to create

  # uncomment below to test the property 
  #expect_equal(model.instance$`projectName`, "EXPECTED_RESULT")
})

test_that("role", {
  # tests for the property `role` (character)
  # the role of the current user in the project

  # uncomment below to test the property 
  #expect_equal(model.instance$`role`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("message", {
  # tests for the property `message` (character)
  # informational message about the project

  # uncomment below to test the property 
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

