# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MethodRepoMethod")

model.instance <- MethodRepoMethod$new()

test_that("methodNamespace", {
  # tests for the property `methodNamespace` (character)
  # The namespace of the method in Agora

  # uncomment below to test the property 
  #expect_equal(model.instance$`methodNamespace`, "EXPECTED_RESULT")
})

test_that("methodName", {
  # tests for the property `methodName` (character)
  # The name of the method in Agora

  # uncomment below to test the property 
  #expect_equal(model.instance$`methodName`, "EXPECTED_RESULT")
})

test_that("methodVersion", {
  # tests for the property `methodVersion` (integer)
  # The integer method version in Agora (or a string method version for Dockstore)

  # uncomment below to test the property 
  #expect_equal(model.instance$`methodVersion`, "EXPECTED_RESULT")
})

test_that("methodPath", {
  # tests for the property `methodPath` (character)
  # The path of the method in Dockstore

  # uncomment below to test the property 
  #expect_equal(model.instance$`methodPath`, "EXPECTED_RESULT")
})

test_that("sourceRepo", {
  # tests for the property `sourceRepo` (character)
  # The method&#39;s repository, currently one of \&quot;agora\&quot; or \&quot;dockstore\&quot;

  # uncomment below to test the property 
  #expect_equal(model.instance$`sourceRepo`, "EXPECTED_RESULT")
})

test_that("methodUri", {
  # tests for the property `methodUri` (character)
  # URI that specifies the method&#39;s repository and captures all the information necessary to identify the method within its repository (e.g. agora://namespace/name/1, dockstore://path/version)

  # uncomment below to test the property 
  #expect_equal(model.instance$`methodUri`, "EXPECTED_RESULT")
})

