# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RawlsGroupRef")

model.instance <- RawlsGroupRef$new()

test_that("groupName", {
  # tests for the property `groupName` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`groupName`, "EXPECTED_RESULT")
})

