# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UserInfo")

model.instance <- UserInfo$new()

test_that("userSubjectId", {
  # tests for the property `userSubjectId` (character)
  # User&#39;s ID (subject id from Google)

  # uncomment below to test the property 
  #expect_equal(model.instance$`userSubjectId`, "EXPECTED_RESULT")
})

test_that("userEmail", {
  # tests for the property `userEmail` (character)
  # User&#39;s email

  # uncomment below to test the property 
  #expect_equal(model.instance$`userEmail`, "EXPECTED_RESULT")
})

