# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test WorkflowCost")

model.instance <- WorkflowCost$new()

test_that("cost", {
  # tests for the property `cost` (numeric)
  # Workflow cost

  # uncomment below to test the property 
  #expect_equal(model.instance$`cost`, "EXPECTED_RESULT")
})

test_that("workflowId", {
  # tests for the property `workflowId` (character)
  # The id of this workflow

  # uncomment below to test the property 
  #expect_equal(model.instance$`workflowId`, "EXPECTED_RESULT")
})

