# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test JWTWrapper")

model.instance <- JWTWrapper$new()

test_that("jwt", {
  # tests for the property `jwt` (character)
  # the encoded/signed JWT

  # uncomment below to test the property 
  #expect_equal(model.instance$`jwt`, "EXPECTED_RESULT")
})

