# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PublishConfigurationIngest")

model.instance <- PublishConfigurationIngest$new()

test_that("configurationNamespace", {
  # tests for the property `configurationNamespace` (character)
  # Method configuration namespace

  # uncomment below to test the property 
  #expect_equal(model.instance$`configurationNamespace`, "EXPECTED_RESULT")
})

test_that("configurationName", {
  # tests for the property `configurationName` (character)
  # Method configuration name

  # uncomment below to test the property 
  #expect_equal(model.instance$`configurationName`, "EXPECTED_RESULT")
})

test_that("sourceNamespace", {
  # tests for the property `sourceNamespace` (character)
  # Method configuration source namespace

  # uncomment below to test the property 
  #expect_equal(model.instance$`sourceNamespace`, "EXPECTED_RESULT")
})

test_that("sourceName", {
  # tests for the property `sourceName` (character)
  # Method configuration source name

  # uncomment below to test the property 
  #expect_equal(model.instance$`sourceName`, "EXPECTED_RESULT")
})

