# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ProfileApi")

api.instance <- ProfileApi$new()

test_that("Billing", {
  # tests for Billing
  # base path: http://localhost
  # List billing projects for a user
  # @return [array[BillingProjectMembership]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("BillingAccounts", {
  # tests for BillingAccounts
  # base path: http://localhost
  # List billing accounts for a user
  # @return [array[BillingAccount]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("BillingProjectStatus", {
  # tests for BillingProjectStatus
  # base path: http://localhost
  # billing project status
  # billing project status
  # @param project.name character Name of the billing project
  # @return [BillingProjectStatus]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetAll", {
  # tests for GetAll
  # base path: http://localhost
  # Returns a list of all keys and values stored in the user profile service for the currently logged-in user.
  # @return [RegisterProfile]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetProxyGroup", {
  # tests for GetProxyGroup
  # base path: http://localhost
  # Returns the proxy group email for the current user
  # @param email character User email whose proxy group to retrieve
  # @return [character]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetTerraPreference", {
  # tests for GetTerraPreference
  # base path: http://localhost
  # Returns the current user&#39;s preference for Terra UI vs. Legacy view
  # @return [TerraPreference]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetUserStatus", {
  # tests for GetUserStatus
  # base path: http://localhost
  # Passes through to the Rawls userinfo API and returns its response
  # @return [RawlsMe]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ImportStatus", {
  # tests for ImportStatus
  # base path: http://localhost
  # Check the user&#39;s ability to import a method config into a workspace
  # @return [UserImportPermission]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("IsCurator", {
  # tests for IsCurator
  # base path: http://localhost
  # Query to see if you&#39;re a library curator
  # gets the curator status of a user
  # @return [CuratorStatus]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Me", {
  # tests for Me
  # base path: http://localhost
  # Returns registration and activation status for the current user
  # @param user.details.only character when set to true does not check the various enabled statuses of the user (optional)
  # @return [Me]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SetFCPreference", {
  # tests for SetFCPreference
  # base path: http://localhost
  # Sets the current user&#39;s preference to use Legacy view, not Terra UI
  # @return [TerraPreference]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SetProfile", {
  # tests for SetProfile
  # base path: http://localhost
  # Sets a profile object in the user profile service for the currently logged-in user.
  # @param profile Profile A complete profile (optional)
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SetTerraPreference", {
  # tests for SetTerraPreference
  # base path: http://localhost
  # Sets the current user&#39;s preference to use Terra UI, not Legacy view
  # @return [TerraPreference]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateProfile", {
  # tests for UpdateProfile
  # base path: http://localhost
  # Update the preferences for the user
  # @param preferences map(character) The preferences to set as a Map[String, String]
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UserInfo", {
  # tests for UserInfo
  # base path: http://localhost
  # Passes through to Google&#39;s userinfo API and returns its response
  # See https://developers.google.com/+/web/api/rest/openidconnect/getOpenIdConnect for response info. Userinfo endpoint lives at https://www.googleapis.com/oauth2/v3/userinfo. 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

