# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VersionApi")

api.instance <- VersionApi$new()

test_that("ExecutionEngineVersion", {
  # tests for ExecutionEngineVersion
  # base path: http://localhost
  # Returns the currently deployed version of FireCloud&#39;s execution engine
  # @return [ExecutionEngineVersion]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("OrchestrationVersion", {
  # tests for OrchestrationVersion
  # base path: http://localhost
  # Returns the currently deployed version of this service.
  # @return [OrchestrationVersion]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

