# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ToolDescriptor")

model.instance <- ToolDescriptor$new()

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("descriptor", {
  # tests for the property `descriptor` (character)
  # The descriptor that represents this version of the tool. (WDL)

  # uncomment below to test the property 
  #expect_equal(model.instance$`descriptor`, "EXPECTED_RESULT")
})

test_that("url", {
  # tests for the property `url` (character)
  # Optional url to the tool descriptor used to build this image, should include version information, and can include a git hash (e.g. https://raw.githubusercontent.com/ICGC-TCGA-PanCancer/pcawg_delly_workflow/ea2a5db69bd20a42976838790bc29294df3af02b/delly_docker/Delly.cwl )

  # uncomment below to test the property 
  #expect_equal(model.instance$`url`, "EXPECTED_RESULT")
})

