# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BillingAccountRedirect")

model.instance <- BillingAccountRedirect$new()

test_that("redirect", {
  # tests for the property `redirect` (character)
  # URL to redirect to

  # uncomment below to test the property 
  #expect_equal(model.instance$`redirect`, "EXPECTED_RESULT")
})

