# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CopyConfigurationIngest")

model.instance <- CopyConfigurationIngest$new()

test_that("configurationNamespace", {
  # tests for the property `configurationNamespace` (character)
  # Method configuration namespace

  # uncomment below to test the property 
  #expect_equal(model.instance$`configurationNamespace`, "EXPECTED_RESULT")
})

test_that("configurationName", {
  # tests for the property `configurationName` (character)
  # Method configuration name

  # uncomment below to test the property 
  #expect_equal(model.instance$`configurationName`, "EXPECTED_RESULT")
})

test_that("configurationSnapshotId", {
  # tests for the property `configurationSnapshotId` (integer)
  # Method configuration snapshot id

  # uncomment below to test the property 
  #expect_equal(model.instance$`configurationSnapshotId`, "EXPECTED_RESULT")
})

test_that("destinationNamespace", {
  # tests for the property `destinationNamespace` (character)
  # Method configuration destination namespace

  # uncomment below to test the property 
  #expect_equal(model.instance$`destinationNamespace`, "EXPECTED_RESULT")
})

test_that("destinationName", {
  # tests for the property `destinationName` (character)
  # Method configuration destination name

  # uncomment below to test the property 
  #expect_equal(model.instance$`destinationName`, "EXPECTED_RESULT")
})

