# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Namespace")

model.instance <- Namespace$new()

test_that("namespace", {
  # tests for the property `namespace` (character)
  # Entity namespace

  # uncomment below to test the property 
  #expect_equal(model.instance$`namespace`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # Entity name

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

