# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RawlsMe")

model.instance <- RawlsMe$new()

test_that("userInfo", {
  # tests for the property `userInfo` (UserInfo)

  # uncomment below to test the property 
  #expect_equal(model.instance$`userInfo`, "EXPECTED_RESULT")
})

test_that("enabled", {
  # tests for the property `enabled` (ExtendedEnabled)

  # uncomment below to test the property 
  #expect_equal(model.instance$`enabled`, "EXPECTED_RESULT")
})

