# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NotificationsApi")

api.instance <- NotificationsApi$new()

test_that("GeneralNotifications", {
  # tests for GeneralNotifications
  # base path: http://localhost
  # Gets the general notifications available
  # @return [array[NotificationType]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("WorkspaceNotifications", {
  # tests for WorkspaceNotifications
  # base path: http://localhost
  # Gets the notifications available for a workspace
  # @param workspace.namespace character workspace namespace
  # @param workspace.name character workspace name
  # @return [array[NotificationType]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

