# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SubmissionValidationHeader")

model.instance <- SubmissionValidationHeader$new()

test_that("entityType", {
  # tests for the property `entityType` (character)
  # type of entity

  # uncomment below to test the property 
  #expect_equal(model.instance$`entityType`, "EXPECTED_RESULT")
})

test_that("inputExpressions", {
  # tests for the property `inputExpressions` (array[SubmissionValidationInput])
  # input descriptions

  # uncomment below to test the property 
  #expect_equal(model.instance$`inputExpressions`, "EXPECTED_RESULT")
})

