# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AttributeUpdateOperation")

model.instance <- AttributeUpdateOperation$new()

test_that("op", {
  # tests for the property `op` (character)
  # The operation to perform on the attribute

  # uncomment below to test the property 
  #expect_equal(model.instance$`op`, "EXPECTED_RESULT")
})

