# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test WorkspaceACLUpdateResponse")

model.instance <- WorkspaceACLUpdateResponse$new()

test_that("subjectId", {
  # tests for the property `subjectId` (character)
  # id of the user or group whose permissions will be changed

  # uncomment below to test the property 
  #expect_equal(model.instance$`subjectId`, "EXPECTED_RESULT")
})

test_that("accessLevel", {
  # tests for the property `accessLevel` (character)
  # The access level granted to this user or group (OWNER, READER, WRITER, NO ACCESS)

  # uncomment below to test the property 
  #expect_equal(model.instance$`accessLevel`, "EXPECTED_RESULT")
})

