# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MethodRepositoryApi")

api.instance <- MethodRepositoryApi$new()

test_that("ApiConfigurationsNamespaceNameSnapshotIdDelete", {
  # tests for ApiConfigurationsNamespaceNameSnapshotIdDelete
  # base path: http://localhost
  # Redact a single configuration.
  # Redacts a configuration and all of its associated configurations 
  # @param namespace character Method Configuration Namespace
  # @param name character Method Configuration Name
  # @param snapshot.id character Method Configuration snapshot ID
  # @return [integer]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ApiConfigurationsPost", {
  # tests for ApiConfigurationsPost
  # base path: http://localhost
  # Add a configuration.
  # Inserts a method configuration into the method repository and gives the owner full access permissions. Must supply a namespace, name, payload, and entityType. Cannot supply a snapshotId 
  # @param body ConfigurationQuery Agora Entity (optional)
  # @return [ConfigurationResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ApiMethodsDefinitionsGet", {
  # tests for ApiMethodsDefinitionsGet
  # base path: http://localhost
  # List method definitions
  # List method definitions - i.e. unique namespace/name pairs - with counts of snapshots and associated configurations 
  # @return [array[MethodDefinition]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ApiMethodsNamespaceNameConfigurationsGet", {
  # tests for ApiMethodsNamespaceNameConfigurationsGet
  # base path: http://localhost
  # List configurations associated with a method
  # Given the namespace/name of a method, returns all configurations in the repository that reference that method 
  # @param namespace character Namespace of method.
  # @param name character Name of method.
  # @return [array[ConfigurationResponseWithPayloadObject]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ApiMethodsNamespaceNameSnapshotIdConfigurationsGet", {
  # tests for ApiMethodsNamespaceNameSnapshotIdConfigurationsGet
  # base path: http://localhost
  # List compatible configurations for this method snapshot
  # Returns all configurations that 1. have the exact same input and output arguments as the supplied method snapshot, and 2. reference any snapshot of this method. 
  # @param namespace character Method Namespace
  # @param name character Method Name
  # @param snapshot.id character Method snapshot ID
  # @return [array[ConfigurationResponseWithPayloadObject]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ApiMethodsNamespaceNameSnapshotIdDelete", {
  # tests for ApiMethodsNamespaceNameSnapshotIdDelete
  # base path: http://localhost
  # Redact a single method.
  # Redacts a method and all of its associated configurations 
  # @param namespace character Method Namespace
  # @param name character Method Name
  # @param snapshot.id character Method snapshot ID
  # @return [integer]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ApiMethodsNamespaceNameSnapshotIdGet", {
  # tests for ApiMethodsNamespaceNameSnapshotIdGet
  # base path: http://localhost
  # Find a single method.
  # Returns one method that matches the namespace, name, and snapshotId. 
  # @param namespace character Method Namespace
  # @param name character Method Name
  # @param snapshot.id character Method snapshot ID
  # @param only.payload character Boolean to return only the payload of the method. (optional)
  # @return [MethodResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ApiMethodsNamespaceNameSnapshotIdPost", {
  # tests for ApiMethodsNamespaceNameSnapshotIdPost
  # base path: http://localhost
  # Create a new snapshot of an existing Method.
  # Inserts a new snapshot of the method into the method repository and copies access permissions from previous snapshot, optionally redacting the source snapshot. Documentation, synopsis, and payload are the only arguments considered for the new snapshot; everything else is copied from the source. 
  # @param namespace character Method Namespace
  # @param name character Method Name
  # @param snapshot.id character Method snapshot ID
  # @param redact character Should the source method be redacted? (optional)
  # @param body InlineObject1  (optional)
  # @return [MethodResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ApiMethodsPost", {
  # tests for ApiMethodsPost
  # base path: http://localhost
  # Add a Method.
  # Inserts a method into the method repository and gives the owner full access permissions. Must supply a namespace name, payload, and entityType. Cannot supply a snapshotId 
  # @param body MethodQuery Agora Entity (optional)
  # @return [MethodResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CopyFromMethodRepo", {
  # tests for CopyFromMethodRepo
  # base path: http://localhost
  # Copy a Method Repository Configuration into a workspace
  # @param workspace.namespace character Workspace Namespace
  # @param workspace.name character Workspace Name
  # @param config.to.copy CopyConfigurationIngest Method Configuration to Copy
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CopyToMethodRepo", {
  # tests for CopyToMethodRepo
  # base path: http://localhost
  # Copy a Method Config in a workspace to the Method Repository
  # @param workspace.namespace character Workspace Namespace
  # @param workspace.name character Workspace Name
  # @param config.to.copy PublishConfigurationIngest Method Configuration to Copy
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateMethodTemplate", {
  # tests for CreateMethodTemplate
  # base path: http://localhost
  # Create a Method Configuration template from a Method
  # @param method.name MethodID name of Method to use for template
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetConfigACL", {
  # tests for GetConfigACL
  # base path: http://localhost
  # get ACL permissions on a Method Repository configuration
  # @param namespace character Method Configuration Namespace
  # @param name character Method Configuration Name
  # @param snapshot.id character Method Configuration snapshot ID
  # @return [array[object]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetConfigNamespaceACL", {
  # tests for GetConfigNamespaceACL
  # base path: http://localhost
  # get ACL permissions on a Method Repository Configuration Namespace
  # @param namespace character Method Configuration Namespace
  # @return [array[object]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetMethodACL", {
  # tests for GetMethodACL
  # base path: http://localhost
  # get ACL permissions on a Method Repository method
  # @param namespace character Method Namespace
  # @param name character Method Name
  # @param snapshot.id character Method snapshot ID
  # @return [array[object]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetMethodIO", {
  # tests for GetMethodIO
  # base path: http://localhost
  # Get information about a method&#39;s inputs and outputs
  # @param method.name MethodID name of Method to look up
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetMethodNamespaceACL", {
  # tests for GetMethodNamespaceACL
  # base path: http://localhost
  # get ACL permissions on a Method Repository Method Namespace
  # @param namespace character Method Namespace
  # @return [array[object]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetMethodRepositoryConfiguration", {
  # tests for GetMethodRepositoryConfiguration
  # base path: http://localhost
  # Get a Method Repository configuration
  # @param namespace character Method Configuration Namespace
  # @param name character Method Configuration Name
  # @param snapshot.id character Method Configuration snapshot ID
  # @param payload.as.object character Instead of returning a string under key payload, return a JSON object under key payloadObject (optional)
  # @return [ConfigurationResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListMethodRepositoryConfigurations", {
  # tests for ListMethodRepositoryConfigurations
  # base path: http://localhost
  # List Method Repository configurations. 
  # The configurations endpoint returns all configurations the requester has permissions to read that fit the filter criteria. 
  # @param namespace character Namespace of configuration. (optional)
  # @param name character Name of configuration. (optional)
  # @param snapshot.id integer Snapshot ID of configuration. (optional)
  # @param snapshot.comment character Snapshot comment of AgoraEntity (optional)
  # @param synopsis character Synopsis of configuration. (optional)
  # @param documentation character Documentation of configuration. (optional)
  # @param owner character Owner of configuration. (optional)
  # @param payload character Payload of configuration in WDL. (optional)
  # @param entity.type character Type of configuration - Task or Workflow (optional)
  # @return [array[ConfigurationResponse]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListMethodRepositoryMethods", {
  # tests for ListMethodRepositoryMethods
  # base path: http://localhost
  # Lists Method Repository methods. 
  # @param namespace character Namespace of method. (optional)
  # @param name character Name of method. (optional)
  # @param snapshot.id integer Snapshot ID of method. (optional)
  # @param snapshot.comment character Snapshot comment of AgoraEntity (optional)
  # @param synopsis character Synopsis of method. (optional)
  # @param documentation character Documentation of method. (optional)
  # @param owner character Owner of method. (optional)
  # @param payload character Payload of method in WDL. (optional)
  # @param entity.type character Type of Method - Task or Workflow (optional)
  # @return [array[MethodResponse]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MultiUpsertMethodsACL", {
  # tests for MultiUpsertMethodsACL
  # base path: http://localhost
  # set ACLs for multiple methods in one call
  # @param methodacls array[MethodAclPair] method acls to upsert
  # @return [array[MethodAclPair]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SetConfigACL", {
  # tests for SetConfigACL
  # base path: http://localhost
  # set ACL permissions on a Method Repository configuration
  # @param namespace character Method Configuration Namespace
  # @param name character Method Configuration Name
  # @param snapshot.id character Method Configuration snapshot ID
  # @param payload array[object] the ACLs to upsert
  # @return [array[object]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SetConfigNamespaceACL", {
  # tests for SetConfigNamespaceACL
  # base path: http://localhost
  # set ACL permissions on a Method Repository Configuration Namespace
  # @param namespace character Method Configuration Namespace
  # @param payload array[object] the ACLs to upsert
  # @return [array[Array]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SetMethodACL", {
  # tests for SetMethodACL
  # base path: http://localhost
  # set ACL permissions on a Method Repository method
  # @param namespace character Method Namespace
  # @param name character Method Name
  # @param snapshot.id character Method snapshot ID
  # @param payload array[object] the ACLs to upsert
  # @return [array[object]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SetMethodNamespaceACL", {
  # tests for SetMethodNamespaceACL
  # base path: http://localhost
  # set ACL permissions on a Method Repository Method Namespace
  # @param namespace character Method Namespace
  # @param payload array[object] the ACLs to upsert
  # @return [array[object]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

