# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Metadata")

model.instance <- Metadata$new()

test_that("version", {
  # tests for the property `version` (character)
  # The version of this registry

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("api-version", {
  # tests for the property `api-version` (character)
  # The version of the GA4GH tool-registry API supported by this registry

  # uncomment below to test the property 
  #expect_equal(model.instance$`api-version`, "EXPECTED_RESULT")
})

test_that("country", {
  # tests for the property `country` (character)
  # A country code for the registry (ISO 3166-1 alpha-3)

  # uncomment below to test the property 
  #expect_equal(model.instance$`country`, "EXPECTED_RESULT")
})

test_that("friendly-name", {
  # tests for the property `friendly-name` (character)
  # A friendly name that can be used in addition to the hostname to describe a registry

  # uncomment below to test the property 
  #expect_equal(model.instance$`friendly-name`, "EXPECTED_RESULT")
})

