# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test WorkspaceCatalogResponse")

model.instance <- WorkspaceCatalogResponse$new()

test_that("subjectId", {
  # tests for the property `subjectId` (character)
  # subject id of the user or group whose permissions were changed

  # uncomment below to test the property 
  #expect_equal(model.instance$`subjectId`, "EXPECTED_RESULT")
})

test_that("catalog", {
  # tests for the property `catalog` (character)
  # Set to true if you want this user to be able to perform library related operations on the workspace

  # uncomment below to test the property 
  #expect_equal(model.instance$`catalog`, "EXPECTED_RESULT")
})

