# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Workspace")

model.instance <- Workspace$new()

test_that("namespace", {
  # tests for the property `namespace` (character)
  # The namespace the workspace belongs to

  # uncomment below to test the property 
  #expect_equal(model.instance$`namespace`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # The name of the workspace

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("authorizationDomain", {
  # tests for the property `authorizationDomain` (array[ManagedGroupRef])
  # The list of groups to form the Authorization Domain (empty if no Authorization Domain is set)

  # uncomment below to test the property 
  #expect_equal(model.instance$`authorizationDomain`, "EXPECTED_RESULT")
})

test_that("workspaceId", {
  # tests for the property `workspaceId` (character)
  # A UUID associated with the workspace

  # uncomment below to test the property 
  #expect_equal(model.instance$`workspaceId`, "EXPECTED_RESULT")
})

test_that("bucketName", {
  # tests for the property `bucketName` (character)
  # The name of the bucket associated with the workspace

  # uncomment below to test the property 
  #expect_equal(model.instance$`bucketName`, "EXPECTED_RESULT")
})

test_that("createdDate", {
  # tests for the property `createdDate` (character)
  # The date the workspace was created in yyyy-MM-ddTHH:mm:ss.SSSZZ format

  # uncomment below to test the property 
  #expect_equal(model.instance$`createdDate`, "EXPECTED_RESULT")
})

test_that("lastModified", {
  # tests for the property `lastModified` (character)
  # The date the workspace was last modified in yyyy-MM-ddTHH:mm:ss.SSSZZ format

  # uncomment below to test the property 
  #expect_equal(model.instance$`lastModified`, "EXPECTED_RESULT")
})

test_that("createdBy", {
  # tests for the property `createdBy` (character)
  # The user who created the workspace

  # uncomment below to test the property 
  #expect_equal(model.instance$`createdBy`, "EXPECTED_RESULT")
})

test_that("attributes", {
  # tests for the property `attributes` (map(character))
  # Map[String, Attribute]

  # uncomment below to test the property 
  #expect_equal(model.instance$`attributes`, "EXPECTED_RESULT")
})

test_that("accessLevels", {
  # tests for the property `accessLevels` (map(RawlsGroupRef))
  # Map[String, RawlsGroupRef]

  # uncomment below to test the property 
  #expect_equal(model.instance$`accessLevels`, "EXPECTED_RESULT")
})

test_that("authDomainACLs", {
  # tests for the property `authDomainACLs` (map(RawlsGroupRef))
  # Map[String, RawlsGroupRef]

  # uncomment below to test the property 
  #expect_equal(model.instance$`authDomainACLs`, "EXPECTED_RESULT")
})

test_that("isLocked", {
  # tests for the property `isLocked` (character)
  # Can the Workspace currently be modified?

  # uncomment below to test the property 
  #expect_equal(model.instance$`isLocked`, "EXPECTED_RESULT")
})

