# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NewMethodConfigIngest")

model.instance <- NewMethodConfigIngest$new()

test_that("namespace", {
  # tests for the property `namespace` (character)
  # Method configuration namespace

  # uncomment below to test the property 
  #expect_equal(model.instance$`namespace`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # Method configuration name

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("rootEntityType", {
  # tests for the property `rootEntityType` (character)
  # Method configuration root entity type

  # uncomment below to test the property 
  #expect_equal(model.instance$`rootEntityType`, "EXPECTED_RESULT")
})

test_that("inputs", {
  # tests for the property `inputs` (map(character))
  # Input map - Map[string, string]

  # uncomment below to test the property 
  #expect_equal(model.instance$`inputs`, "EXPECTED_RESULT")
})

test_that("outputs", {
  # tests for the property `outputs` (map(character))
  # Output map - Map[string, string]

  # uncomment below to test the property 
  #expect_equal(model.instance$`outputs`, "EXPECTED_RESULT")
})

test_that("prerequisites", {
  # tests for the property `prerequisites` (map(character))
  # Prerequisites map - Map[string, string]

  # uncomment below to test the property 
  #expect_equal(model.instance$`prerequisites`, "EXPECTED_RESULT")
})

test_that("methodRepoMethod", {
  # tests for the property `methodRepoMethod` (map(character))
  # Method ID - Map

  # uncomment below to test the property 
  #expect_equal(model.instance$`methodRepoMethod`, "EXPECTED_RESULT")
})

test_that("methodConfigVersion", {
  # tests for the property `methodConfigVersion` (integer)
  # Version number, incremented on edit

  # uncomment below to test the property 
  #expect_equal(model.instance$`methodConfigVersion`, "EXPECTED_RESULT")
})

test_that("deleted", {
  # tests for the property `deleted` (character)
  # Is this config marked as deleted?

  # uncomment below to test the property 
  #expect_equal(model.instance$`deleted`, "EXPECTED_RESULT")
})

