# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ValueTypeObjectFieldTypes")

model.instance <- ValueTypeObjectFieldTypes$new()

test_that("fieldName", {
  # tests for the property `fieldName` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`fieldName`, "EXPECTED_RESULT")
})

test_that("fieldType", {
  # tests for the property `fieldType` (ValueType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`fieldType`, "EXPECTED_RESULT")
})

