# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ConfigurationQuery")

model.instance <- ConfigurationQuery$new()

test_that("namespace", {
  # tests for the property `namespace` (character)
  # Namespace which contains Configuration.

  # uncomment below to test the property 
  #expect_equal(model.instance$`namespace`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # Name of the Configuration.

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("synopsis", {
  # tests for the property `synopsis` (character)
  # Synopsis which contains Configuration.

  # uncomment below to test the property 
  #expect_equal(model.instance$`synopsis`, "EXPECTED_RESULT")
})

test_that("snapshotComment", {
  # tests for the property `snapshotComment` (character)
  # Snapshot comment of AgoraEntity

  # uncomment below to test the property 
  #expect_equal(model.instance$`snapshotComment`, "EXPECTED_RESULT")
})

test_that("documentation", {
  # tests for the property `documentation` (character)
  # Documentation of the Configuration.

  # uncomment below to test the property 
  #expect_equal(model.instance$`documentation`, "EXPECTED_RESULT")
})

test_that("payload", {
  # tests for the property `payload` (character)
  # Payload of method -- must be in WDL format

  # uncomment below to test the property 
  #expect_equal(model.instance$`payload`, "EXPECTED_RESULT")
})

test_that("entityType", {
  # tests for the property `entityType` (character)
  # Can only be Configuration.

  # uncomment below to test the property 
  #expect_equal(model.instance$`entityType`, "EXPECTED_RESULT")
})

