# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test WorkspaceListResponse")

model.instance <- WorkspaceListResponse$new()

test_that("accessLevel", {
  # tests for the property `accessLevel` (WorkspaceAccessLevel)

  # uncomment below to test the property 
  #expect_equal(model.instance$`accessLevel`, "EXPECTED_RESULT")
})

test_that("public", {
  # tests for the property `public` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`public`, "EXPECTED_RESULT")
})

test_that("workspace", {
  # tests for the property `workspace` (WorkspaceDetails)

  # uncomment below to test the property 
  #expect_equal(model.instance$`workspace`, "EXPECTED_RESULT")
})

test_that("workspaceSubmissionStats", {
  # tests for the property `workspaceSubmissionStats` (WorkspaceSubmissionStats)

  # uncomment below to test the property 
  #expect_equal(model.instance$`workspaceSubmissionStats`, "EXPECTED_RESULT")
})

