# FireCloud
#
# FireCloud API 
#
# The version of the OpenAPI document: 0.1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AddListMember
#'
#' @description AddListMember Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field op  character 
#'
#' @field attributeListName  character [optional]
#'
#' @field newMember  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AddListMember <- R6::R6Class(
  'AddListMember',
  public = list(
    `op` = NULL,
    `attributeListName` = NULL,
    `newMember` = NULL,
    initialize = function(
        `op`, `attributeListName`=NULL, `newMember`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`op`)) {
        stopifnot(is.character(`op`), length(`op`) == 1)
        self$`op` <- `op`
      }
      if (!is.null(`attributeListName`)) {
        stopifnot(is.character(`attributeListName`), length(`attributeListName`) == 1)
        self$`attributeListName` <- `attributeListName`
      }
      if (!is.null(`newMember`)) {
        stopifnot(is.character(`newMember`), length(`newMember`) == 1)
        self$`newMember` <- `newMember`
      }
    },
    toJSON = function() {
      AddListMemberObject <- list()
      if (!is.null(self$`op`)) {
        AddListMemberObject[['op']] <-
          self$`op`
      }
      if (!is.null(self$`attributeListName`)) {
        AddListMemberObject[['attributeListName']] <-
          self$`attributeListName`
      }
      if (!is.null(self$`newMember`)) {
        AddListMemberObject[['newMember']] <-
          self$`newMember`
      }

      AddListMemberObject
    },
    fromJSON = function(AddListMemberJson) {
      AddListMemberObject <- jsonlite::fromJSON(AddListMemberJson)
      if (!is.null(AddListMemberObject$`op`)) {
        self$`op` <- AddListMemberObject$`op`
      }
      if (!is.null(AddListMemberObject$`attributeListName`)) {
        self$`attributeListName` <- AddListMemberObject$`attributeListName`
      }
      if (!is.null(AddListMemberObject$`newMember`)) {
        self$`newMember` <- AddListMemberObject$`newMember`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`op`)) {
        sprintf(
        '"op":
          "%s"
                ',
        self$`op`
        )},
        if (!is.null(self$`attributeListName`)) {
        sprintf(
        '"attributeListName":
          "%s"
                ',
        self$`attributeListName`
        )},
        if (!is.null(self$`newMember`)) {
        sprintf(
        '"newMember":
          "%s"
                ',
        self$`newMember`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AddListMemberJson) {
      AddListMemberObject <- jsonlite::fromJSON(AddListMemberJson)
      self$`op` <- AddListMemberObject$`op`
      self$`attributeListName` <- AddListMemberObject$`attributeListName`
      self$`newMember` <- AddListMemberObject$`newMember`
      self
    }
  )
)

