# FireCloud
#
# FireCloud API 
#
# The version of the OpenAPI document: 0.1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ConfigurationPayloadMethodRepoMethod
#'
#' @description ConfigurationPayloadMethodRepoMethod Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field methodName  character [optional]
#'
#' @field methodNamespace  character [optional]
#'
#' @field methodVersion  integer [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ConfigurationPayloadMethodRepoMethod <- R6::R6Class(
  'ConfigurationPayloadMethodRepoMethod',
  public = list(
    `methodName` = NULL,
    `methodNamespace` = NULL,
    `methodVersion` = NULL,
    initialize = function(
        `methodName`='cancer_exome_pipeline_v2', `methodNamespace`='broad-dsde-dev,', `methodVersion`=1, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`methodName`)) {
        stopifnot(is.character(`methodName`), length(`methodName`) == 1)
        self$`methodName` <- `methodName`
      }
      if (!is.null(`methodNamespace`)) {
        stopifnot(is.character(`methodNamespace`), length(`methodNamespace`) == 1)
        self$`methodNamespace` <- `methodNamespace`
      }
      if (!is.null(`methodVersion`)) {
        stopifnot(is.numeric(`methodVersion`), length(`methodVersion`) == 1)
        self$`methodVersion` <- `methodVersion`
      }
    },
    toJSON = function() {
      ConfigurationPayloadMethodRepoMethodObject <- list()
      if (!is.null(self$`methodName`)) {
        ConfigurationPayloadMethodRepoMethodObject[['methodName']] <-
          self$`methodName`
      }
      if (!is.null(self$`methodNamespace`)) {
        ConfigurationPayloadMethodRepoMethodObject[['methodNamespace']] <-
          self$`methodNamespace`
      }
      if (!is.null(self$`methodVersion`)) {
        ConfigurationPayloadMethodRepoMethodObject[['methodVersion']] <-
          self$`methodVersion`
      }

      ConfigurationPayloadMethodRepoMethodObject
    },
    fromJSON = function(ConfigurationPayloadMethodRepoMethodJson) {
      ConfigurationPayloadMethodRepoMethodObject <- jsonlite::fromJSON(ConfigurationPayloadMethodRepoMethodJson)
      if (!is.null(ConfigurationPayloadMethodRepoMethodObject$`methodName`)) {
        self$`methodName` <- ConfigurationPayloadMethodRepoMethodObject$`methodName`
      }
      if (!is.null(ConfigurationPayloadMethodRepoMethodObject$`methodNamespace`)) {
        self$`methodNamespace` <- ConfigurationPayloadMethodRepoMethodObject$`methodNamespace`
      }
      if (!is.null(ConfigurationPayloadMethodRepoMethodObject$`methodVersion`)) {
        self$`methodVersion` <- ConfigurationPayloadMethodRepoMethodObject$`methodVersion`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`methodName`)) {
        sprintf(
        '"methodName":
          "%s"
                ',
        self$`methodName`
        )},
        if (!is.null(self$`methodNamespace`)) {
        sprintf(
        '"methodNamespace":
          "%s"
                ',
        self$`methodNamespace`
        )},
        if (!is.null(self$`methodVersion`)) {
        sprintf(
        '"methodVersion":
          %d
                ',
        self$`methodVersion`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ConfigurationPayloadMethodRepoMethodJson) {
      ConfigurationPayloadMethodRepoMethodObject <- jsonlite::fromJSON(ConfigurationPayloadMethodRepoMethodJson)
      self$`methodName` <- ConfigurationPayloadMethodRepoMethodObject$`methodName`
      self$`methodNamespace` <- ConfigurationPayloadMethodRepoMethodObject$`methodNamespace`
      self$`methodVersion` <- ConfigurationPayloadMethodRepoMethodObject$`methodVersion`
      self
    }
  )
)

