# FireCloud
#
# FireCloud API 
#
# The version of the OpenAPI document: 0.1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CreateRawlsBillingProjectFullRequest
#'
#' @description CreateRawlsBillingProjectFullRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field projectName  character 
#'
#' @field billingAccount  character 
#'
#' @field highSecurityNetwork  character [optional]
#'
#' @field enableFlowLogs  character [optional]
#'
#' @field privateIpGoogleAccess  character [optional]
#'
#' @field servicePerimeter  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CreateRawlsBillingProjectFullRequest <- R6::R6Class(
  'CreateRawlsBillingProjectFullRequest',
  public = list(
    `projectName` = NULL,
    `billingAccount` = NULL,
    `highSecurityNetwork` = NULL,
    `enableFlowLogs` = NULL,
    `privateIpGoogleAccess` = NULL,
    `servicePerimeter` = NULL,
    initialize = function(
        `projectName`, `billingAccount`, `highSecurityNetwork`=NULL, `enableFlowLogs`=NULL, `privateIpGoogleAccess`=NULL, `servicePerimeter`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`projectName`)) {
        stopifnot(is.character(`projectName`), length(`projectName`) == 1)
        self$`projectName` <- `projectName`
      }
      if (!missing(`billingAccount`)) {
        stopifnot(is.character(`billingAccount`), length(`billingAccount`) == 1)
        self$`billingAccount` <- `billingAccount`
      }
      if (!is.null(`highSecurityNetwork`)) {
        self$`highSecurityNetwork` <- `highSecurityNetwork`
      }
      if (!is.null(`enableFlowLogs`)) {
        self$`enableFlowLogs` <- `enableFlowLogs`
      }
      if (!is.null(`privateIpGoogleAccess`)) {
        self$`privateIpGoogleAccess` <- `privateIpGoogleAccess`
      }
      if (!is.null(`servicePerimeter`)) {
        stopifnot(is.character(`servicePerimeter`), length(`servicePerimeter`) == 1)
        self$`servicePerimeter` <- `servicePerimeter`
      }
    },
    toJSON = function() {
      CreateRawlsBillingProjectFullRequestObject <- list()
      if (!is.null(self$`projectName`)) {
        CreateRawlsBillingProjectFullRequestObject[['projectName']] <-
          self$`projectName`
      }
      if (!is.null(self$`billingAccount`)) {
        CreateRawlsBillingProjectFullRequestObject[['billingAccount']] <-
          self$`billingAccount`
      }
      if (!is.null(self$`highSecurityNetwork`)) {
        CreateRawlsBillingProjectFullRequestObject[['highSecurityNetwork']] <-
          self$`highSecurityNetwork`
      }
      if (!is.null(self$`enableFlowLogs`)) {
        CreateRawlsBillingProjectFullRequestObject[['enableFlowLogs']] <-
          self$`enableFlowLogs`
      }
      if (!is.null(self$`privateIpGoogleAccess`)) {
        CreateRawlsBillingProjectFullRequestObject[['privateIpGoogleAccess']] <-
          self$`privateIpGoogleAccess`
      }
      if (!is.null(self$`servicePerimeter`)) {
        CreateRawlsBillingProjectFullRequestObject[['servicePerimeter']] <-
          self$`servicePerimeter`
      }

      CreateRawlsBillingProjectFullRequestObject
    },
    fromJSON = function(CreateRawlsBillingProjectFullRequestJson) {
      CreateRawlsBillingProjectFullRequestObject <- jsonlite::fromJSON(CreateRawlsBillingProjectFullRequestJson)
      if (!is.null(CreateRawlsBillingProjectFullRequestObject$`projectName`)) {
        self$`projectName` <- CreateRawlsBillingProjectFullRequestObject$`projectName`
      }
      if (!is.null(CreateRawlsBillingProjectFullRequestObject$`billingAccount`)) {
        self$`billingAccount` <- CreateRawlsBillingProjectFullRequestObject$`billingAccount`
      }
      if (!is.null(CreateRawlsBillingProjectFullRequestObject$`highSecurityNetwork`)) {
        self$`highSecurityNetwork` <- CreateRawlsBillingProjectFullRequestObject$`highSecurityNetwork`
      }
      if (!is.null(CreateRawlsBillingProjectFullRequestObject$`enableFlowLogs`)) {
        self$`enableFlowLogs` <- CreateRawlsBillingProjectFullRequestObject$`enableFlowLogs`
      }
      if (!is.null(CreateRawlsBillingProjectFullRequestObject$`privateIpGoogleAccess`)) {
        self$`privateIpGoogleAccess` <- CreateRawlsBillingProjectFullRequestObject$`privateIpGoogleAccess`
      }
      if (!is.null(CreateRawlsBillingProjectFullRequestObject$`servicePerimeter`)) {
        self$`servicePerimeter` <- CreateRawlsBillingProjectFullRequestObject$`servicePerimeter`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`projectName`)) {
        sprintf(
        '"projectName":
          "%s"
                ',
        self$`projectName`
        )},
        if (!is.null(self$`billingAccount`)) {
        sprintf(
        '"billingAccount":
          "%s"
                ',
        self$`billingAccount`
        )},
        if (!is.null(self$`highSecurityNetwork`)) {
        sprintf(
        '"highSecurityNetwork":
          "%s"
                ',
        self$`highSecurityNetwork`
        )},
        if (!is.null(self$`enableFlowLogs`)) {
        sprintf(
        '"enableFlowLogs":
          "%s"
                ',
        self$`enableFlowLogs`
        )},
        if (!is.null(self$`privateIpGoogleAccess`)) {
        sprintf(
        '"privateIpGoogleAccess":
          "%s"
                ',
        self$`privateIpGoogleAccess`
        )},
        if (!is.null(self$`servicePerimeter`)) {
        sprintf(
        '"servicePerimeter":
          "%s"
                ',
        self$`servicePerimeter`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CreateRawlsBillingProjectFullRequestJson) {
      CreateRawlsBillingProjectFullRequestObject <- jsonlite::fromJSON(CreateRawlsBillingProjectFullRequestJson)
      self$`projectName` <- CreateRawlsBillingProjectFullRequestObject$`projectName`
      self$`billingAccount` <- CreateRawlsBillingProjectFullRequestObject$`billingAccount`
      self$`highSecurityNetwork` <- CreateRawlsBillingProjectFullRequestObject$`highSecurityNetwork`
      self$`enableFlowLogs` <- CreateRawlsBillingProjectFullRequestObject$`enableFlowLogs`
      self$`privateIpGoogleAccess` <- CreateRawlsBillingProjectFullRequestObject$`privateIpGoogleAccess`
      self$`servicePerimeter` <- CreateRawlsBillingProjectFullRequestObject$`servicePerimeter`
      self
    }
  )
)

