# FireCloud
#
# FireCloud API 
#
# The version of the OpenAPI document: 0.1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CreateAttributeEntityReferenceListAllOf
#'
#' @description CreateAttributeEntityReferenceListAllOf Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field attributeListName  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CreateAttributeEntityReferenceListAllOf <- R6::R6Class(
  'CreateAttributeEntityReferenceListAllOf',
  public = list(
    `attributeListName` = NULL,
    initialize = function(
        `attributeListName`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`attributeListName`)) {
        stopifnot(is.character(`attributeListName`), length(`attributeListName`) == 1)
        self$`attributeListName` <- `attributeListName`
      }
    },
    toJSON = function() {
      CreateAttributeEntityReferenceListAllOfObject <- list()
      if (!is.null(self$`attributeListName`)) {
        CreateAttributeEntityReferenceListAllOfObject[['attributeListName']] <-
          self$`attributeListName`
      }

      CreateAttributeEntityReferenceListAllOfObject
    },
    fromJSON = function(CreateAttributeEntityReferenceListAllOfJson) {
      CreateAttributeEntityReferenceListAllOfObject <- jsonlite::fromJSON(CreateAttributeEntityReferenceListAllOfJson)
      if (!is.null(CreateAttributeEntityReferenceListAllOfObject$`attributeListName`)) {
        self$`attributeListName` <- CreateAttributeEntityReferenceListAllOfObject$`attributeListName`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`attributeListName`)) {
        sprintf(
        '"attributeListName":
          "%s"
                ',
        self$`attributeListName`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CreateAttributeEntityReferenceListAllOfJson) {
      CreateAttributeEntityReferenceListAllOfObject <- jsonlite::fromJSON(CreateAttributeEntityReferenceListAllOfJson)
      self$`attributeListName` <- CreateAttributeEntityReferenceListAllOfObject$`attributeListName`
      self
    }
  )
)

