# FireCloud
#
# FireCloud API 
#
# The version of the OpenAPI document: 0.1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title EntityID
#'
#' @description EntityID Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field entityType  character [optional]
#'
#' @field entityName  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EntityID <- R6::R6Class(
  'EntityID',
  public = list(
    `entityType` = NULL,
    `entityName` = NULL,
    initialize = function(
        `entityType`=NULL, `entityName`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`entityType`)) {
        stopifnot(is.character(`entityType`), length(`entityType`) == 1)
        self$`entityType` <- `entityType`
      }
      if (!is.null(`entityName`)) {
        stopifnot(is.character(`entityName`), length(`entityName`) == 1)
        self$`entityName` <- `entityName`
      }
    },
    toJSON = function() {
      EntityIDObject <- list()
      if (!is.null(self$`entityType`)) {
        EntityIDObject[['entityType']] <-
          self$`entityType`
      }
      if (!is.null(self$`entityName`)) {
        EntityIDObject[['entityName']] <-
          self$`entityName`
      }

      EntityIDObject
    },
    fromJSON = function(EntityIDJson) {
      EntityIDObject <- jsonlite::fromJSON(EntityIDJson)
      if (!is.null(EntityIDObject$`entityType`)) {
        self$`entityType` <- EntityIDObject$`entityType`
      }
      if (!is.null(EntityIDObject$`entityName`)) {
        self$`entityName` <- EntityIDObject$`entityName`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`entityType`)) {
        sprintf(
        '"entityType":
          "%s"
                ',
        self$`entityType`
        )},
        if (!is.null(self$`entityName`)) {
        sprintf(
        '"entityName":
          "%s"
                ',
        self$`entityName`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(EntityIDJson) {
      EntityIDObject <- jsonlite::fromJSON(EntityIDJson)
      self$`entityType` <- EntityIDObject$`entityType`
      self$`entityName` <- EntityIDObject$`entityName`
      self
    }
  )
)

