# FireCloud
#
# FireCloud API 
#
# The version of the OpenAPI document: 0.1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineObject5
#'
#' @description InlineObject5 Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field code  character 
#'
#' @field redirectUri  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineObject5 <- R6::R6Class(
  'InlineObject5',
  public = list(
    `code` = NULL,
    `redirectUri` = NULL,
    initialize = function(
        `code`, `redirectUri`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`code`)) {
        stopifnot(is.character(`code`), length(`code`) == 1)
        self$`code` <- `code`
      }
      if (!missing(`redirectUri`)) {
        stopifnot(is.character(`redirectUri`), length(`redirectUri`) == 1)
        self$`redirectUri` <- `redirectUri`
      }
    },
    toJSON = function() {
      InlineObject5Object <- list()
      if (!is.null(self$`code`)) {
        InlineObject5Object[['code']] <-
          self$`code`
      }
      if (!is.null(self$`redirectUri`)) {
        InlineObject5Object[['redirectUri']] <-
          self$`redirectUri`
      }

      InlineObject5Object
    },
    fromJSON = function(InlineObject5Json) {
      InlineObject5Object <- jsonlite::fromJSON(InlineObject5Json)
      if (!is.null(InlineObject5Object$`code`)) {
        self$`code` <- InlineObject5Object$`code`
      }
      if (!is.null(InlineObject5Object$`redirectUri`)) {
        self$`redirectUri` <- InlineObject5Object$`redirectUri`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`code`)) {
        sprintf(
        '"code":
          "%s"
                ',
        self$`code`
        )},
        if (!is.null(self$`redirectUri`)) {
        sprintf(
        '"redirectUri":
          "%s"
                ',
        self$`redirectUri`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineObject5Json) {
      InlineObject5Object <- jsonlite::fromJSON(InlineObject5Json)
      self$`code` <- InlineObject5Object$`code`
      self$`redirectUri` <- InlineObject5Object$`redirectUri`
      self
    }
  )
)

