# FireCloud
#
# FireCloud API 
#
# The version of the OpenAPI document: 0.1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MethodConfigurationName
#'
#' @description MethodConfigurationName Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field namespace  character 
#'
#' @field name  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MethodConfigurationName <- R6::R6Class(
  'MethodConfigurationName',
  public = list(
    `namespace` = NULL,
    `name` = NULL,
    initialize = function(
        `namespace`, `name`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`namespace`)) {
        stopifnot(is.character(`namespace`), length(`namespace`) == 1)
        self$`namespace` <- `namespace`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      MethodConfigurationNameObject <- list()
      if (!is.null(self$`namespace`)) {
        MethodConfigurationNameObject[['namespace']] <-
          self$`namespace`
      }
      if (!is.null(self$`name`)) {
        MethodConfigurationNameObject[['name']] <-
          self$`name`
      }

      MethodConfigurationNameObject
    },
    fromJSON = function(MethodConfigurationNameJson) {
      MethodConfigurationNameObject <- jsonlite::fromJSON(MethodConfigurationNameJson)
      if (!is.null(MethodConfigurationNameObject$`namespace`)) {
        self$`namespace` <- MethodConfigurationNameObject$`namespace`
      }
      if (!is.null(MethodConfigurationNameObject$`name`)) {
        self$`name` <- MethodConfigurationNameObject$`name`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`namespace`)) {
        sprintf(
        '"namespace":
          "%s"
                ',
        self$`namespace`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MethodConfigurationNameJson) {
      MethodConfigurationNameObject <- jsonlite::fromJSON(MethodConfigurationNameJson)
      self$`namespace` <- MethodConfigurationNameObject$`namespace`
      self$`name` <- MethodConfigurationNameObject$`name`
      self
    }
  )
)

