# FireCloud
#
# FireCloud API 
#
# The version of the OpenAPI document: 0.1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MethodShort
#'
#' @description MethodShort Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field managers  list( character ) 
#'
#' @field namespace  character 
#'
#' @field name  character 
#'
#' @field snapshotId  integer 
#'
#' @field public  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MethodShort <- R6::R6Class(
  'MethodShort',
  public = list(
    `managers` = NULL,
    `namespace` = NULL,
    `name` = NULL,
    `snapshotId` = NULL,
    `public` = NULL,
    initialize = function(
        `managers`, `namespace`, `name`, `snapshotId`, `public`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`managers`)) {
        stopifnot(is.vector(`managers`), length(`managers`) != 0)
        sapply(`managers`, function(x) stopifnot(is.character(x)))
        self$`managers` <- `managers`
      }
      if (!missing(`namespace`)) {
        stopifnot(is.character(`namespace`), length(`namespace`) == 1)
        self$`namespace` <- `namespace`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`snapshotId`)) {
        stopifnot(is.numeric(`snapshotId`), length(`snapshotId`) == 1)
        self$`snapshotId` <- `snapshotId`
      }
      if (!is.null(`public`)) {
        self$`public` <- `public`
      }
    },
    toJSON = function() {
      MethodShortObject <- list()
      if (!is.null(self$`managers`)) {
        MethodShortObject[['managers']] <-
          self$`managers`
      }
      if (!is.null(self$`namespace`)) {
        MethodShortObject[['namespace']] <-
          self$`namespace`
      }
      if (!is.null(self$`name`)) {
        MethodShortObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`snapshotId`)) {
        MethodShortObject[['snapshotId']] <-
          self$`snapshotId`
      }
      if (!is.null(self$`public`)) {
        MethodShortObject[['public']] <-
          self$`public`
      }

      MethodShortObject
    },
    fromJSON = function(MethodShortJson) {
      MethodShortObject <- jsonlite::fromJSON(MethodShortJson)
      if (!is.null(MethodShortObject$`managers`)) {
        self$`managers` <- ApiClient$new()$deserializeObj(MethodShortObject$`managers`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(MethodShortObject$`namespace`)) {
        self$`namespace` <- MethodShortObject$`namespace`
      }
      if (!is.null(MethodShortObject$`name`)) {
        self$`name` <- MethodShortObject$`name`
      }
      if (!is.null(MethodShortObject$`snapshotId`)) {
        self$`snapshotId` <- MethodShortObject$`snapshotId`
      }
      if (!is.null(MethodShortObject$`public`)) {
        self$`public` <- MethodShortObject$`public`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`managers`)) {
        sprintf(
        '"managers":
           [%s]
        ',
        paste(unlist(lapply(self$`managers`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`namespace`)) {
        sprintf(
        '"namespace":
          "%s"
                ',
        self$`namespace`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`snapshotId`)) {
        sprintf(
        '"snapshotId":
          %d
                ',
        self$`snapshotId`
        )},
        if (!is.null(self$`public`)) {
        sprintf(
        '"public":
          "%s"
                ',
        self$`public`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MethodShortJson) {
      MethodShortObject <- jsonlite::fromJSON(MethodShortJson)
      self$`managers` <- ApiClient$new()$deserializeObj(MethodShortObject$`managers`, "array[character]", loadNamespace("openapi"))
      self$`namespace` <- MethodShortObject$`namespace`
      self$`name` <- MethodShortObject$`name`
      self$`snapshotId` <- MethodShortObject$`snapshotId`
      self$`public` <- MethodShortObject$`public`
      self
    }
  )
)

