# FireCloud
#
# FireCloud API 
#
# The version of the OpenAPI document: 0.1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title PublishConfigurationIngest
#'
#' @description PublishConfigurationIngest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field configurationNamespace  character 
#'
#' @field configurationName  character 
#'
#' @field sourceNamespace  character 
#'
#' @field sourceName  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PublishConfigurationIngest <- R6::R6Class(
  'PublishConfigurationIngest',
  public = list(
    `configurationNamespace` = NULL,
    `configurationName` = NULL,
    `sourceNamespace` = NULL,
    `sourceName` = NULL,
    initialize = function(
        `configurationNamespace`, `configurationName`, `sourceNamespace`, `sourceName`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`configurationNamespace`)) {
        stopifnot(is.character(`configurationNamespace`), length(`configurationNamespace`) == 1)
        self$`configurationNamespace` <- `configurationNamespace`
      }
      if (!missing(`configurationName`)) {
        stopifnot(is.character(`configurationName`), length(`configurationName`) == 1)
        self$`configurationName` <- `configurationName`
      }
      if (!missing(`sourceNamespace`)) {
        stopifnot(is.character(`sourceNamespace`), length(`sourceNamespace`) == 1)
        self$`sourceNamespace` <- `sourceNamespace`
      }
      if (!missing(`sourceName`)) {
        stopifnot(is.character(`sourceName`), length(`sourceName`) == 1)
        self$`sourceName` <- `sourceName`
      }
    },
    toJSON = function() {
      PublishConfigurationIngestObject <- list()
      if (!is.null(self$`configurationNamespace`)) {
        PublishConfigurationIngestObject[['configurationNamespace']] <-
          self$`configurationNamespace`
      }
      if (!is.null(self$`configurationName`)) {
        PublishConfigurationIngestObject[['configurationName']] <-
          self$`configurationName`
      }
      if (!is.null(self$`sourceNamespace`)) {
        PublishConfigurationIngestObject[['sourceNamespace']] <-
          self$`sourceNamespace`
      }
      if (!is.null(self$`sourceName`)) {
        PublishConfigurationIngestObject[['sourceName']] <-
          self$`sourceName`
      }

      PublishConfigurationIngestObject
    },
    fromJSON = function(PublishConfigurationIngestJson) {
      PublishConfigurationIngestObject <- jsonlite::fromJSON(PublishConfigurationIngestJson)
      if (!is.null(PublishConfigurationIngestObject$`configurationNamespace`)) {
        self$`configurationNamespace` <- PublishConfigurationIngestObject$`configurationNamespace`
      }
      if (!is.null(PublishConfigurationIngestObject$`configurationName`)) {
        self$`configurationName` <- PublishConfigurationIngestObject$`configurationName`
      }
      if (!is.null(PublishConfigurationIngestObject$`sourceNamespace`)) {
        self$`sourceNamespace` <- PublishConfigurationIngestObject$`sourceNamespace`
      }
      if (!is.null(PublishConfigurationIngestObject$`sourceName`)) {
        self$`sourceName` <- PublishConfigurationIngestObject$`sourceName`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`configurationNamespace`)) {
        sprintf(
        '"configurationNamespace":
          "%s"
                ',
        self$`configurationNamespace`
        )},
        if (!is.null(self$`configurationName`)) {
        sprintf(
        '"configurationName":
          "%s"
                ',
        self$`configurationName`
        )},
        if (!is.null(self$`sourceNamespace`)) {
        sprintf(
        '"sourceNamespace":
          "%s"
                ',
        self$`sourceNamespace`
        )},
        if (!is.null(self$`sourceName`)) {
        sprintf(
        '"sourceName":
          "%s"
                ',
        self$`sourceName`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(PublishConfigurationIngestJson) {
      PublishConfigurationIngestObject <- jsonlite::fromJSON(PublishConfigurationIngestJson)
      self$`configurationNamespace` <- PublishConfigurationIngestObject$`configurationNamespace`
      self$`configurationName` <- PublishConfigurationIngestObject$`configurationName`
      self$`sourceNamespace` <- PublishConfigurationIngestObject$`sourceNamespace`
      self$`sourceName` <- PublishConfigurationIngestObject$`sourceName`
      self
    }
  )
)

