# FireCloud
#
# FireCloud API 
#
# The version of the OpenAPI document: 0.1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RawlsGroupRef
#'
#' @description RawlsGroupRef Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field groupName  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RawlsGroupRef <- R6::R6Class(
  'RawlsGroupRef',
  public = list(
    `groupName` = NULL,
    initialize = function(
        `groupName`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`groupName`)) {
        stopifnot(is.character(`groupName`), length(`groupName`) == 1)
        self$`groupName` <- `groupName`
      }
    },
    toJSON = function() {
      RawlsGroupRefObject <- list()
      if (!is.null(self$`groupName`)) {
        RawlsGroupRefObject[['groupName']] <-
          self$`groupName`
      }

      RawlsGroupRefObject
    },
    fromJSON = function(RawlsGroupRefJson) {
      RawlsGroupRefObject <- jsonlite::fromJSON(RawlsGroupRefJson)
      if (!is.null(RawlsGroupRefObject$`groupName`)) {
        self$`groupName` <- RawlsGroupRefObject$`groupName`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`groupName`)) {
        sprintf(
        '"groupName":
          "%s"
                ',
        self$`groupName`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RawlsGroupRefJson) {
      RawlsGroupRefObject <- jsonlite::fromJSON(RawlsGroupRefJson)
      self$`groupName` <- RawlsGroupRefObject$`groupName`
      self
    }
  )
)

