# FireCloud
#
# FireCloud API 
#
# The version of the OpenAPI document: 0.1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Storage operations
#' @description openapi.Storage
#' @format An \code{R6Class} generator object
#' @field apiClient Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ GetMetadata } \emph{ Get metadata about an object stored in GCS.  }
#' Returns a subset of the metadata available from Google&#39;s Cloud Storage JSON API, as well as the estimated egress charge to North America. If you need the full metadata, we recommend you use Google&#39;s API directly; see https://cloud.google.com/storage/docs/json_api/v1/objects/get. 
#'
#' \itemize{
#' \item \emph{ @param } bucket character
#' \item \emph{ @param } object character
#'
#'
#' \item status code : 200 | Success
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | Not Found
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | Internal Error
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetStorageDownload } \emph{ Download GCS object using a cookie token  }
#' Download GCS object using a cookie token 
#'
#' \itemize{
#' \item \emph{ @param } bucket character
#' \item \emph{ @param } object character
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : data.frame 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 404 | Not Found
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 500 | Internal Error
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  GetMetadata  ####################
#'
#' library(openapi)
#' var.bucket <- 'bucket_example' # character | Name of the bucket in which the object resides.
#' var.object <- 'object_example' # character | Name of the object. (be sure to urlencode)
#'
#' #Get metadata about an object stored in GCS. 
#' api.instance <- StorageApi$new()
#'
#' # Configure OAuth2 access token for authorization: googleoauth
#' api.instance$apiClient$accessToken <- 'TODO_YOUR_ACCESS_TOKEN';
#'
#' result <- api.instance$GetMetadata(var.bucket, var.object)
#'
#'
#' ####################  GetStorageDownload  ####################
#'
#' library(openapi)
#' var.bucket <- 'bucket_example' # character | Name of the bucket in which the object resides.
#' var.object <- 'object_example' # character | Name of the object. (be sure to urlencode)
#'
#' #Download GCS object using a cookie token 
#' api.instance <- StorageApi$new()
#'
#' # Configure OAuth2 access token for authorization: googleoauth
#' api.instance$apiClient$accessToken <- 'TODO_YOUR_ACCESS_TOKEN';
#'
#' result <- api.instance$GetStorageDownload(var.bucket, var.object)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
StorageApi <- R6::R6Class(
  'StorageApi',
  public = list(
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    GetMetadata = function(bucket, object, ...){
      apiResponse <- self$GetMetadataWithHttpInfo(bucket, object, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetMetadataWithHttpInfo = function(bucket, object, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`bucket`)) {
        stop("Missing required parameter `bucket`.")
      }

      if (missing(`object`)) {
        stop("Missing required parameter `object`.")
      }

      body <- NULL
      urlPath <- "/api/storage/{bucket}/{object}"
      if (!missing(`bucket`)) {
        urlPath <- gsub(paste0("\\{", "bucket", "\\}"), URLencode(as.character(`bucket`), reserved = TRUE), urlPath)
      }

      if (!missing(`object`)) {
        urlPath <- gsub(paste0("\\{", "object", "\\}"), URLencode(as.character(`object`), reserved = TRUE), urlPath)
      }

      # OAuth token
      headerParams['Authorization'] <- paste("Bearer", self$apiClient$accessToken, sep=" ")

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        ApiResponse$new(NULL, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetStorageDownload = function(bucket, object, ...){
      apiResponse <- self$GetStorageDownloadWithHttpInfo(bucket, object, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetStorageDownloadWithHttpInfo = function(bucket, object, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`bucket`)) {
        stop("Missing required parameter `bucket`.")
      }

      if (missing(`object`)) {
        stop("Missing required parameter `object`.")
      }

      body <- NULL
      urlPath <- "/cookie-authed/download/b/{bucket}/o/{object}"
      if (!missing(`bucket`)) {
        urlPath <- gsub(paste0("\\{", "bucket", "\\}"), URLencode(as.character(`bucket`), reserved = TRUE), urlPath)
      }

      if (!missing(`object`)) {
        urlPath <- gsub(paste0("\\{", "object", "\\}"), URLencode(as.character(`object`), reserved = TRUE), urlPath)
      }

      # OAuth token
      headerParams['Authorization'] <- paste("Bearer", self$apiClient$accessToken, sep=" ")

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "data.frame", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    }
  )
)
