# FireCloud
#
# FireCloud API 
#
# The version of the OpenAPI document: 0.1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SubmissionValidationInput
#'
#' @description SubmissionValidationInput Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field wdlName  character 
#'
#' @field expression  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SubmissionValidationInput <- R6::R6Class(
  'SubmissionValidationInput',
  public = list(
    `wdlName` = NULL,
    `expression` = NULL,
    initialize = function(
        `wdlName`, `expression`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`wdlName`)) {
        stopifnot(is.character(`wdlName`), length(`wdlName`) == 1)
        self$`wdlName` <- `wdlName`
      }
      if (!missing(`expression`)) {
        stopifnot(is.character(`expression`), length(`expression`) == 1)
        self$`expression` <- `expression`
      }
    },
    toJSON = function() {
      SubmissionValidationInputObject <- list()
      if (!is.null(self$`wdlName`)) {
        SubmissionValidationInputObject[['wdlName']] <-
          self$`wdlName`
      }
      if (!is.null(self$`expression`)) {
        SubmissionValidationInputObject[['expression']] <-
          self$`expression`
      }

      SubmissionValidationInputObject
    },
    fromJSON = function(SubmissionValidationInputJson) {
      SubmissionValidationInputObject <- jsonlite::fromJSON(SubmissionValidationInputJson)
      if (!is.null(SubmissionValidationInputObject$`wdlName`)) {
        self$`wdlName` <- SubmissionValidationInputObject$`wdlName`
      }
      if (!is.null(SubmissionValidationInputObject$`expression`)) {
        self$`expression` <- SubmissionValidationInputObject$`expression`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`wdlName`)) {
        sprintf(
        '"wdlName":
          "%s"
                ',
        self$`wdlName`
        )},
        if (!is.null(self$`expression`)) {
        sprintf(
        '"expression":
          "%s"
                ',
        self$`expression`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SubmissionValidationInputJson) {
      SubmissionValidationInputObject <- jsonlite::fromJSON(SubmissionValidationInputJson)
      self$`wdlName` <- SubmissionValidationInputObject$`wdlName`
      self$`expression` <- SubmissionValidationInputObject$`expression`
      self
    }
  )
)

