# FireCloud
#
# FireCloud API 
#
# The version of the OpenAPI document: 0.1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ValueTypeObjectFieldTypes
#'
#' @description ValueTypeObjectFieldTypes Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field fieldName  character [optional]
#'
#' @field fieldType  \link{ValueType} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ValueTypeObjectFieldTypes <- R6::R6Class(
  'ValueTypeObjectFieldTypes',
  public = list(
    `fieldName` = NULL,
    `fieldType` = NULL,
    initialize = function(
        `fieldName`=NULL, `fieldType`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`fieldName`)) {
        stopifnot(is.character(`fieldName`), length(`fieldName`) == 1)
        self$`fieldName` <- `fieldName`
      }
      if (!is.null(`fieldType`)) {
        stopifnot(R6::is.R6(`fieldType`))
        self$`fieldType` <- `fieldType`
      }
    },
    toJSON = function() {
      ValueTypeObjectFieldTypesObject <- list()
      if (!is.null(self$`fieldName`)) {
        ValueTypeObjectFieldTypesObject[['fieldName']] <-
          self$`fieldName`
      }
      if (!is.null(self$`fieldType`)) {
        ValueTypeObjectFieldTypesObject[['fieldType']] <-
          self$`fieldType`$toJSON()
      }

      ValueTypeObjectFieldTypesObject
    },
    fromJSON = function(ValueTypeObjectFieldTypesJson) {
      ValueTypeObjectFieldTypesObject <- jsonlite::fromJSON(ValueTypeObjectFieldTypesJson)
      if (!is.null(ValueTypeObjectFieldTypesObject$`fieldName`)) {
        self$`fieldName` <- ValueTypeObjectFieldTypesObject$`fieldName`
      }
      if (!is.null(ValueTypeObjectFieldTypesObject$`fieldType`)) {
        fieldTypeObject <- ValueType$new()
        fieldTypeObject$fromJSON(jsonlite::toJSON(ValueTypeObjectFieldTypesObject$fieldType, auto_unbox = TRUE, digits = NA))
        self$`fieldType` <- fieldTypeObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`fieldName`)) {
        sprintf(
        '"fieldName":
          "%s"
                ',
        self$`fieldName`
        )},
        if (!is.null(self$`fieldType`)) {
        sprintf(
        '"fieldType":
        %s
        ',
        jsonlite::toJSON(self$`fieldType`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ValueTypeObjectFieldTypesJson) {
      ValueTypeObjectFieldTypesObject <- jsonlite::fromJSON(ValueTypeObjectFieldTypesJson)
      self$`fieldName` <- ValueTypeObjectFieldTypesObject$`fieldName`
      self$`fieldType` <- ValueType$new()$fromJSON(jsonlite::toJSON(ValueTypeObjectFieldTypesObject$fieldType, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

