# FireCloud
#
# FireCloud API 
#
# The version of the OpenAPI document: 0.1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title VersionResponse
#'
#' @description VersionResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field cromwell  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
VersionResponse <- R6::R6Class(
  'VersionResponse',
  public = list(
    `cromwell` = NULL,
    initialize = function(
        `cromwell`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`cromwell`)) {
        stopifnot(is.character(`cromwell`), length(`cromwell`) == 1)
        self$`cromwell` <- `cromwell`
      }
    },
    toJSON = function() {
      VersionResponseObject <- list()
      if (!is.null(self$`cromwell`)) {
        VersionResponseObject[['cromwell']] <-
          self$`cromwell`
      }

      VersionResponseObject
    },
    fromJSON = function(VersionResponseJson) {
      VersionResponseObject <- jsonlite::fromJSON(VersionResponseJson)
      if (!is.null(VersionResponseObject$`cromwell`)) {
        self$`cromwell` <- VersionResponseObject$`cromwell`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`cromwell`)) {
        sprintf(
        '"cromwell":
          "%s"
                ',
        self$`cromwell`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(VersionResponseJson) {
      VersionResponseObject <- jsonlite::fromJSON(VersionResponseJson)
      self$`cromwell` <- VersionResponseObject$`cromwell`
      self
    }
  )
)

