# FireCloud
#
# FireCloud API 
#
# The version of the OpenAPI document: 0.1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title WorkspaceResponse
#'
#' @description WorkspaceResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field accessLevel  \link{WorkspaceAccessLevel} [optional]
#'
#' @field bucketOptions  \link{WorkspaceBucketOptions} [optional]
#'
#' @field canCompute  character [optional]
#'
#' @field canShare  character [optional]
#'
#' @field catalog  character [optional]
#'
#' @field owners  list( character ) [optional]
#'
#' @field workspace  \link{WorkspaceDetails} [optional]
#'
#' @field workspaceSubmissionStats  \link{WorkspaceSubmissionStats} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
WorkspaceResponse <- R6::R6Class(
  'WorkspaceResponse',
  public = list(
    `accessLevel` = NULL,
    `bucketOptions` = NULL,
    `canCompute` = NULL,
    `canShare` = NULL,
    `catalog` = NULL,
    `owners` = NULL,
    `workspace` = NULL,
    `workspaceSubmissionStats` = NULL,
    initialize = function(
        `accessLevel`=NULL, `bucketOptions`=NULL, `canCompute`=NULL, `canShare`=NULL, `catalog`=NULL, `owners`=NULL, `workspace`=NULL, `workspaceSubmissionStats`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`accessLevel`)) {
        stopifnot(R6::is.R6(`accessLevel`))
        self$`accessLevel` <- `accessLevel`
      }
      if (!is.null(`bucketOptions`)) {
        stopifnot(R6::is.R6(`bucketOptions`))
        self$`bucketOptions` <- `bucketOptions`
      }
      if (!is.null(`canCompute`)) {
        self$`canCompute` <- `canCompute`
      }
      if (!is.null(`canShare`)) {
        self$`canShare` <- `canShare`
      }
      if (!is.null(`catalog`)) {
        self$`catalog` <- `catalog`
      }
      if (!is.null(`owners`)) {
        stopifnot(is.vector(`owners`), length(`owners`) != 0)
        sapply(`owners`, function(x) stopifnot(is.character(x)))
        self$`owners` <- `owners`
      }
      if (!is.null(`workspace`)) {
        stopifnot(R6::is.R6(`workspace`))
        self$`workspace` <- `workspace`
      }
      if (!is.null(`workspaceSubmissionStats`)) {
        stopifnot(R6::is.R6(`workspaceSubmissionStats`))
        self$`workspaceSubmissionStats` <- `workspaceSubmissionStats`
      }
    },
    toJSON = function() {
      WorkspaceResponseObject <- list()
      if (!is.null(self$`accessLevel`)) {
        WorkspaceResponseObject[['accessLevel']] <-
          self$`accessLevel`$toJSON()
      }
      if (!is.null(self$`bucketOptions`)) {
        WorkspaceResponseObject[['bucketOptions']] <-
          self$`bucketOptions`$toJSON()
      }
      if (!is.null(self$`canCompute`)) {
        WorkspaceResponseObject[['canCompute']] <-
          self$`canCompute`
      }
      if (!is.null(self$`canShare`)) {
        WorkspaceResponseObject[['canShare']] <-
          self$`canShare`
      }
      if (!is.null(self$`catalog`)) {
        WorkspaceResponseObject[['catalog']] <-
          self$`catalog`
      }
      if (!is.null(self$`owners`)) {
        WorkspaceResponseObject[['owners']] <-
          self$`owners`
      }
      if (!is.null(self$`workspace`)) {
        WorkspaceResponseObject[['workspace']] <-
          self$`workspace`$toJSON()
      }
      if (!is.null(self$`workspaceSubmissionStats`)) {
        WorkspaceResponseObject[['workspaceSubmissionStats']] <-
          self$`workspaceSubmissionStats`$toJSON()
      }

      WorkspaceResponseObject
    },
    fromJSON = function(WorkspaceResponseJson) {
      WorkspaceResponseObject <- jsonlite::fromJSON(WorkspaceResponseJson)
      if (!is.null(WorkspaceResponseObject$`accessLevel`)) {
        accessLevelObject <- WorkspaceAccessLevel$new()
        accessLevelObject$fromJSON(jsonlite::toJSON(WorkspaceResponseObject$accessLevel, auto_unbox = TRUE, digits = NA))
        self$`accessLevel` <- accessLevelObject
      }
      if (!is.null(WorkspaceResponseObject$`bucketOptions`)) {
        bucketOptionsObject <- WorkspaceBucketOptions$new()
        bucketOptionsObject$fromJSON(jsonlite::toJSON(WorkspaceResponseObject$bucketOptions, auto_unbox = TRUE, digits = NA))
        self$`bucketOptions` <- bucketOptionsObject
      }
      if (!is.null(WorkspaceResponseObject$`canCompute`)) {
        self$`canCompute` <- WorkspaceResponseObject$`canCompute`
      }
      if (!is.null(WorkspaceResponseObject$`canShare`)) {
        self$`canShare` <- WorkspaceResponseObject$`canShare`
      }
      if (!is.null(WorkspaceResponseObject$`catalog`)) {
        self$`catalog` <- WorkspaceResponseObject$`catalog`
      }
      if (!is.null(WorkspaceResponseObject$`owners`)) {
        self$`owners` <- ApiClient$new()$deserializeObj(WorkspaceResponseObject$`owners`, "array[character]", loadNamespace("openapi"))
      }
      if (!is.null(WorkspaceResponseObject$`workspace`)) {
        workspaceObject <- WorkspaceDetails$new()
        workspaceObject$fromJSON(jsonlite::toJSON(WorkspaceResponseObject$workspace, auto_unbox = TRUE, digits = NA))
        self$`workspace` <- workspaceObject
      }
      if (!is.null(WorkspaceResponseObject$`workspaceSubmissionStats`)) {
        workspaceSubmissionStatsObject <- WorkspaceSubmissionStats$new()
        workspaceSubmissionStatsObject$fromJSON(jsonlite::toJSON(WorkspaceResponseObject$workspaceSubmissionStats, auto_unbox = TRUE, digits = NA))
        self$`workspaceSubmissionStats` <- workspaceSubmissionStatsObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`accessLevel`)) {
        sprintf(
        '"accessLevel":
        %s
        ',
        jsonlite::toJSON(self$`accessLevel`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`bucketOptions`)) {
        sprintf(
        '"bucketOptions":
        %s
        ',
        jsonlite::toJSON(self$`bucketOptions`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`canCompute`)) {
        sprintf(
        '"canCompute":
          "%s"
                ',
        self$`canCompute`
        )},
        if (!is.null(self$`canShare`)) {
        sprintf(
        '"canShare":
          "%s"
                ',
        self$`canShare`
        )},
        if (!is.null(self$`catalog`)) {
        sprintf(
        '"catalog":
          "%s"
                ',
        self$`catalog`
        )},
        if (!is.null(self$`owners`)) {
        sprintf(
        '"owners":
           [%s]
        ',
        paste(unlist(lapply(self$`owners`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`workspace`)) {
        sprintf(
        '"workspace":
        %s
        ',
        jsonlite::toJSON(self$`workspace`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`workspaceSubmissionStats`)) {
        sprintf(
        '"workspaceSubmissionStats":
        %s
        ',
        jsonlite::toJSON(self$`workspaceSubmissionStats`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(WorkspaceResponseJson) {
      WorkspaceResponseObject <- jsonlite::fromJSON(WorkspaceResponseJson)
      self$`accessLevel` <- WorkspaceAccessLevel$new()$fromJSON(jsonlite::toJSON(WorkspaceResponseObject$accessLevel, auto_unbox = TRUE, digits = NA))
      self$`bucketOptions` <- WorkspaceBucketOptions$new()$fromJSON(jsonlite::toJSON(WorkspaceResponseObject$bucketOptions, auto_unbox = TRUE, digits = NA))
      self$`canCompute` <- WorkspaceResponseObject$`canCompute`
      self$`canShare` <- WorkspaceResponseObject$`canShare`
      self$`catalog` <- WorkspaceResponseObject$`catalog`
      self$`owners` <- ApiClient$new()$deserializeObj(WorkspaceResponseObject$`owners`, "array[character]", loadNamespace("openapi"))
      self$`workspace` <- WorkspaceDetails$new()$fromJSON(jsonlite::toJSON(WorkspaceResponseObject$workspace, auto_unbox = TRUE, digits = NA))
      self$`workspaceSubmissionStats` <- WorkspaceSubmissionStats$new()$fromJSON(jsonlite::toJSON(WorkspaceResponseObject$workspaceSubmissionStats, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

