# FireCloud
#
# FireCloud API 
#
# The version of the OpenAPI document: 0.1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title WorkspaceACLUpdateResponse
#'
#' @description WorkspaceACLUpdateResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field subjectId  character 
#'
#' @field accessLevel  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
WorkspaceACLUpdateResponse <- R6::R6Class(
  'WorkspaceACLUpdateResponse',
  public = list(
    `subjectId` = NULL,
    `accessLevel` = NULL,
    initialize = function(
        `subjectId`, `accessLevel`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`subjectId`)) {
        stopifnot(is.character(`subjectId`), length(`subjectId`) == 1)
        self$`subjectId` <- `subjectId`
      }
      if (!missing(`accessLevel`)) {
        stopifnot(is.character(`accessLevel`), length(`accessLevel`) == 1)
        self$`accessLevel` <- `accessLevel`
      }
    },
    toJSON = function() {
      WorkspaceACLUpdateResponseObject <- list()
      if (!is.null(self$`subjectId`)) {
        WorkspaceACLUpdateResponseObject[['subjectId']] <-
          self$`subjectId`
      }
      if (!is.null(self$`accessLevel`)) {
        WorkspaceACLUpdateResponseObject[['accessLevel']] <-
          self$`accessLevel`
      }

      WorkspaceACLUpdateResponseObject
    },
    fromJSON = function(WorkspaceACLUpdateResponseJson) {
      WorkspaceACLUpdateResponseObject <- jsonlite::fromJSON(WorkspaceACLUpdateResponseJson)
      if (!is.null(WorkspaceACLUpdateResponseObject$`subjectId`)) {
        self$`subjectId` <- WorkspaceACLUpdateResponseObject$`subjectId`
      }
      if (!is.null(WorkspaceACLUpdateResponseObject$`accessLevel`)) {
        self$`accessLevel` <- WorkspaceACLUpdateResponseObject$`accessLevel`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`subjectId`)) {
        sprintf(
        '"subjectId":
          "%s"
                ',
        self$`subjectId`
        )},
        if (!is.null(self$`accessLevel`)) {
        sprintf(
        '"accessLevel":
          "%s"
                ',
        self$`accessLevel`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(WorkspaceACLUpdateResponseJson) {
      WorkspaceACLUpdateResponseObject <- jsonlite::fromJSON(WorkspaceACLUpdateResponseJson)
      self$`subjectId` <- WorkspaceACLUpdateResponseObject$`subjectId`
      self$`accessLevel` <- WorkspaceACLUpdateResponseObject$`accessLevel`
      self
    }
  )
)

