# FireCloud
#
# FireCloud API 
#
# The version of the OpenAPI document: 0.1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title WorkflowCallDiff
#'
#' @description WorkflowCallDiff Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field allowResultReuse  character [optional]
#'
#' @field callFqn  character [optional]
#'
#' @field executionStatus  character [optional]
#'
#' @field jobIndex  numeric [optional]
#'
#' @field workflowId  \link{WorkflowIdParam} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
WorkflowCallDiff <- R6::R6Class(
  'WorkflowCallDiff',
  public = list(
    `allowResultReuse` = NULL,
    `callFqn` = NULL,
    `executionStatus` = NULL,
    `jobIndex` = NULL,
    `workflowId` = NULL,
    initialize = function(
        `allowResultReuse`=NULL, `callFqn`=NULL, `executionStatus`=NULL, `jobIndex`=NULL, `workflowId`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`allowResultReuse`)) {
        self$`allowResultReuse` <- `allowResultReuse`
      }
      if (!is.null(`callFqn`)) {
        stopifnot(is.character(`callFqn`), length(`callFqn`) == 1)
        self$`callFqn` <- `callFqn`
      }
      if (!is.null(`executionStatus`)) {
        stopifnot(is.character(`executionStatus`), length(`executionStatus`) == 1)
        self$`executionStatus` <- `executionStatus`
      }
      if (!is.null(`jobIndex`)) {
        self$`jobIndex` <- `jobIndex`
      }
      if (!is.null(`workflowId`)) {
        stopifnot(R6::is.R6(`workflowId`))
        self$`workflowId` <- `workflowId`
      }
    },
    toJSON = function() {
      WorkflowCallDiffObject <- list()
      if (!is.null(self$`allowResultReuse`)) {
        WorkflowCallDiffObject[['allowResultReuse']] <-
          self$`allowResultReuse`
      }
      if (!is.null(self$`callFqn`)) {
        WorkflowCallDiffObject[['callFqn']] <-
          self$`callFqn`
      }
      if (!is.null(self$`executionStatus`)) {
        WorkflowCallDiffObject[['executionStatus']] <-
          self$`executionStatus`
      }
      if (!is.null(self$`jobIndex`)) {
        WorkflowCallDiffObject[['jobIndex']] <-
          self$`jobIndex`
      }
      if (!is.null(self$`workflowId`)) {
        WorkflowCallDiffObject[['workflowId']] <-
          self$`workflowId`$toJSON()
      }

      WorkflowCallDiffObject
    },
    fromJSON = function(WorkflowCallDiffJson) {
      WorkflowCallDiffObject <- jsonlite::fromJSON(WorkflowCallDiffJson)
      if (!is.null(WorkflowCallDiffObject$`allowResultReuse`)) {
        self$`allowResultReuse` <- WorkflowCallDiffObject$`allowResultReuse`
      }
      if (!is.null(WorkflowCallDiffObject$`callFqn`)) {
        self$`callFqn` <- WorkflowCallDiffObject$`callFqn`
      }
      if (!is.null(WorkflowCallDiffObject$`executionStatus`)) {
        self$`executionStatus` <- WorkflowCallDiffObject$`executionStatus`
      }
      if (!is.null(WorkflowCallDiffObject$`jobIndex`)) {
        self$`jobIndex` <- WorkflowCallDiffObject$`jobIndex`
      }
      if (!is.null(WorkflowCallDiffObject$`workflowId`)) {
        workflowIdObject <- WorkflowIdParam$new()
        workflowIdObject$fromJSON(jsonlite::toJSON(WorkflowCallDiffObject$workflowId, auto_unbox = TRUE, digits = NA))
        self$`workflowId` <- workflowIdObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`allowResultReuse`)) {
        sprintf(
        '"allowResultReuse":
          "%s"
                ',
        self$`allowResultReuse`
        )},
        if (!is.null(self$`callFqn`)) {
        sprintf(
        '"callFqn":
          "%s"
                ',
        self$`callFqn`
        )},
        if (!is.null(self$`executionStatus`)) {
        sprintf(
        '"executionStatus":
          "%s"
                ',
        self$`executionStatus`
        )},
        if (!is.null(self$`jobIndex`)) {
        sprintf(
        '"jobIndex":
          %d
                ',
        self$`jobIndex`
        )},
        if (!is.null(self$`workflowId`)) {
        sprintf(
        '"workflowId":
        %s
        ',
        jsonlite::toJSON(self$`workflowId`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(WorkflowCallDiffJson) {
      WorkflowCallDiffObject <- jsonlite::fromJSON(WorkflowCallDiffJson)
      self$`allowResultReuse` <- WorkflowCallDiffObject$`allowResultReuse`
      self$`callFqn` <- WorkflowCallDiffObject$`callFqn`
      self$`executionStatus` <- WorkflowCallDiffObject$`executionStatus`
      self$`jobIndex` <- WorkflowCallDiffObject$`jobIndex`
      self$`workflowId` <- WorkflowIdParam$new()$fromJSON(jsonlite::toJSON(WorkflowCallDiffObject$workflowId, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

