# FireCloud
#
# FireCloud API 
#
# The version of the OpenAPI document: 0.1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title WorkflowCallDiffCallHashDiff
#'
#' @description WorkflowCallDiffCallHashDiff Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field hashKey  character [optional]
#'
#' @field callA  character [optional]
#'
#' @field callB  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
WorkflowCallDiffCallHashDiff <- R6::R6Class(
  'WorkflowCallDiffCallHashDiff',
  public = list(
    `hashKey` = NULL,
    `callA` = NULL,
    `callB` = NULL,
    initialize = function(
        `hashKey`=NULL, `callA`=NULL, `callB`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`hashKey`)) {
        stopifnot(is.character(`hashKey`), length(`hashKey`) == 1)
        self$`hashKey` <- `hashKey`
      }
      if (!is.null(`callA`)) {
        stopifnot(is.character(`callA`), length(`callA`) == 1)
        self$`callA` <- `callA`
      }
      if (!is.null(`callB`)) {
        stopifnot(is.character(`callB`), length(`callB`) == 1)
        self$`callB` <- `callB`
      }
    },
    toJSON = function() {
      WorkflowCallDiffCallHashDiffObject <- list()
      if (!is.null(self$`hashKey`)) {
        WorkflowCallDiffCallHashDiffObject[['hashKey']] <-
          self$`hashKey`
      }
      if (!is.null(self$`callA`)) {
        WorkflowCallDiffCallHashDiffObject[['callA']] <-
          self$`callA`
      }
      if (!is.null(self$`callB`)) {
        WorkflowCallDiffCallHashDiffObject[['callB']] <-
          self$`callB`
      }

      WorkflowCallDiffCallHashDiffObject
    },
    fromJSON = function(WorkflowCallDiffCallHashDiffJson) {
      WorkflowCallDiffCallHashDiffObject <- jsonlite::fromJSON(WorkflowCallDiffCallHashDiffJson)
      if (!is.null(WorkflowCallDiffCallHashDiffObject$`hashKey`)) {
        self$`hashKey` <- WorkflowCallDiffCallHashDiffObject$`hashKey`
      }
      if (!is.null(WorkflowCallDiffCallHashDiffObject$`callA`)) {
        self$`callA` <- WorkflowCallDiffCallHashDiffObject$`callA`
      }
      if (!is.null(WorkflowCallDiffCallHashDiffObject$`callB`)) {
        self$`callB` <- WorkflowCallDiffCallHashDiffObject$`callB`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`hashKey`)) {
        sprintf(
        '"hashKey":
          "%s"
                ',
        self$`hashKey`
        )},
        if (!is.null(self$`callA`)) {
        sprintf(
        '"callA":
          "%s"
                ',
        self$`callA`
        )},
        if (!is.null(self$`callB`)) {
        sprintf(
        '"callB":
          "%s"
                ',
        self$`callB`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(WorkflowCallDiffCallHashDiffJson) {
      WorkflowCallDiffCallHashDiffObject <- jsonlite::fromJSON(WorkflowCallDiffCallHashDiffJson)
      self$`hashKey` <- WorkflowCallDiffCallHashDiffObject$`hashKey`
      self$`callA` <- WorkflowCallDiffCallHashDiffObject$`callA`
      self$`callB` <- WorkflowCallDiffCallHashDiffObject$`callB`
      self
    }
  )
)

