# FireCloud
#
# FireCloud API 
#
# The version of the OpenAPI document: 0.1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title WorkspaceAccessEntry
#'
#' @description WorkspaceAccessEntry Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field accessLevel  character 
#'
#' @field pending  character 
#'
#' @field canShare  character 
#'
#' @field canCompute  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
WorkspaceAccessEntry <- R6::R6Class(
  'WorkspaceAccessEntry',
  public = list(
    `accessLevel` = NULL,
    `pending` = NULL,
    `canShare` = NULL,
    `canCompute` = NULL,
    initialize = function(
        `accessLevel`, `pending`, `canShare`, `canCompute`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`accessLevel`)) {
        stopifnot(is.character(`accessLevel`), length(`accessLevel`) == 1)
        self$`accessLevel` <- `accessLevel`
      }
      if (!missing(`pending`)) {
        self$`pending` <- `pending`
      }
      if (!missing(`canShare`)) {
        self$`canShare` <- `canShare`
      }
      if (!missing(`canCompute`)) {
        self$`canCompute` <- `canCompute`
      }
    },
    toJSON = function() {
      WorkspaceAccessEntryObject <- list()
      if (!is.null(self$`accessLevel`)) {
        WorkspaceAccessEntryObject[['accessLevel']] <-
          self$`accessLevel`
      }
      if (!is.null(self$`pending`)) {
        WorkspaceAccessEntryObject[['pending']] <-
          self$`pending`
      }
      if (!is.null(self$`canShare`)) {
        WorkspaceAccessEntryObject[['canShare']] <-
          self$`canShare`
      }
      if (!is.null(self$`canCompute`)) {
        WorkspaceAccessEntryObject[['canCompute']] <-
          self$`canCompute`
      }

      WorkspaceAccessEntryObject
    },
    fromJSON = function(WorkspaceAccessEntryJson) {
      WorkspaceAccessEntryObject <- jsonlite::fromJSON(WorkspaceAccessEntryJson)
      if (!is.null(WorkspaceAccessEntryObject$`accessLevel`)) {
        self$`accessLevel` <- WorkspaceAccessEntryObject$`accessLevel`
      }
      if (!is.null(WorkspaceAccessEntryObject$`pending`)) {
        self$`pending` <- WorkspaceAccessEntryObject$`pending`
      }
      if (!is.null(WorkspaceAccessEntryObject$`canShare`)) {
        self$`canShare` <- WorkspaceAccessEntryObject$`canShare`
      }
      if (!is.null(WorkspaceAccessEntryObject$`canCompute`)) {
        self$`canCompute` <- WorkspaceAccessEntryObject$`canCompute`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`accessLevel`)) {
        sprintf(
        '"accessLevel":
          "%s"
                ',
        self$`accessLevel`
        )},
        if (!is.null(self$`pending`)) {
        sprintf(
        '"pending":
          "%s"
                ',
        self$`pending`
        )},
        if (!is.null(self$`canShare`)) {
        sprintf(
        '"canShare":
          "%s"
                ',
        self$`canShare`
        )},
        if (!is.null(self$`canCompute`)) {
        sprintf(
        '"canCompute":
          "%s"
                ',
        self$`canCompute`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(WorkspaceAccessEntryJson) {
      WorkspaceAccessEntryObject <- jsonlite::fromJSON(WorkspaceAccessEntryJson)
      self$`accessLevel` <- WorkspaceAccessEntryObject$`accessLevel`
      self$`pending` <- WorkspaceAccessEntryObject$`pending`
      self$`canShare` <- WorkspaceAccessEntryObject$`canShare`
      self$`canCompute` <- WorkspaceAccessEntryObject$`canCompute`
      self
    }
  )
)

